### ISSUE TITLE
Recognition for HP Blade switches

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#117]
A trivial patch that permits the identification of switches in HP blade enclosures from Blade Network Technologies \(e.g., HP GbE2c Ethernet Blade Switch, etc\).

All this does is get more useful information into the Model field; more work is required to properly support the devices \(I only see one or two ports at present\).

It requires at least the addition of two MIBs from the zipfile via http://www.bladenetwork.net/HP-BladeSystem-2.html, which are:

hpswitchpl.mib
GbE2c-L2L3.mib

However there are later models which come with a different collection of MIBs, and it seems some contain some bits and others contain other bits, and they share a lot of bits in common.  Probably the best approach is to manually merge them, but that brings the headache of keeping them consistent and up to date with the source.  A vimdiff suggests there are few if any conflicts, they have just diverged at some point.

Consider this a placeholder ...

Reported by: jrbinks

Original Ticket: [snmp-info/patches/48](https://sourceforge.net/p/snmp-info/patches/48)

**Comment by ollyg** [comment]
Link in the ticket no longer returns a page, so we need a new place to download these MIBs.

The patch mentions:
- HP-SWITCH-PL-MIB
- BLADETYPE4-NETWORK-MIB

**Comment by jeneric** [comment]
MIBs were already in the netdisco-mibs collection. Applied patch as requested.
