### ISSUE TITLE
LLDP fixes

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#140]
(1) Fix the logic which maps local port (lldpLocPortId/lldpLocPortDesc) to interface index.

Currently it matches only lldpLocPortDesc against ifDescr and ifAlias. However in many switches (e.g. Netgear, Dell) the PortDesc is a user-supplied comment or empty string if no comment has been set. Because SNMP::Info doesn't test for the empty-string case, and because many interfaces will have empty string for ifAlias, it returns an arbitrary interface.

The new logic looks at lldpLocPortId (if non-blank) and then lldpLocPortDesc (ditto). It matches them in turn again ifName, ifDescr and then ifAlias.

Typically ifName is the short port name like "Gi1/0/1" (Cisco) or "1/0/1" (Netgear), and for both those vendors it's the same as the value in lldpLocPortId, at least with the firmware versions I tested.

(2) Fix the logic of the returned remote port name (lldp_port)

Currently it returns lldpRemPortDesc unless the PortIdType is "interfaceName" in which case it returns lldpRemPortId.

However there are switches which set PortIdType to "local" and return the correct port name in lldpRemPortId, but lldpRemPortDesc is either a user-supplied comment or empty string.

The new logic returns lldpRemPortId if PortIdType is either "local" or "interfaceName" but is otherwise unchanged.

More details at <https://sourceforge.net/p/snmp-info/mailman/snmp-info-users/thread/53ABF242.30703%40pobox.com/#msg32507476>

Reported by: bcandler

Original Ticket: [snmp-info/patches/71](https://sourceforge.net/p/snmp-info/patches/71)

**Comment by ollyg** [comment]
I think it's reasonable to assume portType of **local** should behave the same as type **interfaceName**, so I can apply that one line patch.

I defer to @jeneric (and agree on the face of it) that the existing interface matching code is safer. We map to Descr, or failing that to Alias. The patch tries Name first, which may or may not be right. See [Interface Naming Patterns](http://www.irobert.info/display/IRINFO/Understanding+ifDescr,+ifName+and+ifAlias) for the weird and wonderful ways this can go wrong.

**Comment by jeneric** [comment]
The local patch has been added with a slight modification. Timetra test class caught that some devices such as Alcatel/Nokia use the ifIndex with a portType of local. Added a check that uses previous behavior if the lldpRemPortId contains only digits assuming it is an ifIndex. This works with the examples provided as they have '/'
