### ISSUE TITLE
Avocent ACS files for correct  discovery in Netdisco

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#141]
Attached is a perl module for support off the more recent Avocent ACS devices.
It is based on the old Cyclades.pm but uses the (also attached) new MIB file for ACS-es.

Reported by: awijntje

Original Ticket: [snmp-info/patches/72](https://sourceforge.net/p/snmp-info/patches/72)

**Comment by ollyg** [comment]
The attached MIB is the same version as the one in cyclades vendor of netdisco-mibs.

**Comment by jeneric** [comment]
Cyclades MIBs have been updated. Avocent ACS device support for 5000, 6000, and 8000 series has been added to the existing Cyclades class and devices with the Avocent enterprise ID will now utilize this class.
