### ISSUE TITLE
Netdisco Sixnet Switch Support

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#142]
I work with several Sixnet SLX-18MG switches. I have tried to add them to NetDisco v2, and while the port status (up/down) is discovered correctly over SNMP, the MAC addresses are not.

I am not a perl whiz, and so I have followed the documentation, and provided SNMP data as requested, so that support for this device can be added to the perl SNMP::Info module. The required output is attached.

Please let me know if I can provide any more information or test any code. I'm happy to do so.

Reported by: irasnyd

Original Ticket: [snmp-info/patches/73](https://sourceforge.net/p/snmp-info/patches/73)

**Comment by jeneric** [comment]
Support added.
