### ISSUE TITLE
SNMP discovery of edgeOS and VyOS devices

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#144]
I have a few devices in my network that weren't detecting the proper vendor. These are vyos, vyatta, edgerouter, edgeswitch, and force10 (strangely enough).

I had to modify the Info.pm file in SNMP, as well as create some (very crude) .pm files per device to simply report the vendor, for a proper rancid-export. I have attached the .pm files, and below is a diff of Info.pm. The first group is in the layer3 overrides. I had to add force10 into the layer2 section (one device was not detecting properly), and i added asterisk in the layer1 section:

diff -Ebr /home/netdisco/perl5/lib/perl5/SNMP/Info.pm /opt/scripts/netdisco-BeforeUpgrade/Info.pm
27c27
< $VERSION = '3.26';
---
> $VERSION = '3.22';
35c35
< SNMP::Info - Version 3.26
---
> SNMP::Info - Version 3.22
1534a1535,1537
>         30803 => 'SNMP::Info::Layer3::vyatta',
>         41112 => 'SNMP::Info::Layer3::edgerouter',
>       4413 => 'SNMP::Info::Layer3::edgeswitch',
1553a1557
>         6027 => 'SNMP::Info::Layer3::Force10',
1564a1569
>         22736 => 'SNMP::Info::asterisk',

Please let me know if you need any information, or if you can improve thse *.pm files (they do not report much data, it's mainly to allow me to have rancid populate properly)

Reported by: mowlesta

Original Ticket: [snmp-info/patches/75](https://sourceforge.net/p/snmp-info/patches/75)

**Comment by ollyg** [comment]
We already have Layer2::Ubiquiti so that should suffice for edgerouter and edgeswitch. We also have Force10, but there is no Vyatta.

I will have a look at why the existing classes are not matching, and add what's needed.

**Comment by ollyg** [comment]
Well, edgerouter might be Layer3::Ubiquiti but YKWIM.

**Comment by dabeani** [comment]
it will be fine to have EdgeRouter (EdgeOS) support in Netdisco!! still interested because we use a bunch of devices. thank you for the time guys.

**Comment by LBegnaud** [comment]
I'd like to resurrect this issue. I'm looking to finally update our install after making heavy modifications locally (like a dummy) to support UBNT producuts.

The issue seems to boil down to the fact that Ubiquiti uses the same OID for all their products but they don't use the same MIBs. I've got a simple workaround that works in our environment and perhaps could be extended to be more generic.

I don't really understand the structure of this library, but I used trial and error enough to get a working config. @ollyg would you mind if I did a PR with my proposed changes and you can take a look at it?

**Comment by LBegnaud** [comment]
I've done a pull request to include edgemax devices (edgeswitch and edgerouter): https://github.com/netdisco/snmp-info/pull/236

@ollyg let me know if there's anything you want me to clean up on that

I'm going to make a separate issue for vyos devices, so I'm going to include this issue in the PR

**Comment by ollyg** [comment]
Really appreciate this work @LBegnaud - many thanks!!
