### ISSUE TITLE
Move away from RFC*MIB

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#153]
Move all the uses of RFC\*MIB to things like SNMPv2-MIB, IF-MIB, IP-MIB, 
etc.

Reported by: fenner

Original Ticket: [snmp-info/feature-requests/8](https://sourceforge.net/p/snmp-info/feature-requests/8)

**Comment by ollyg** [comment]
Likely not a problem if no-one has piled onto this ticket in a few years. Sleeping...
