### ISSUE TITLE
3-Com, H3C, new HP

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#171]
Please add support for 3-Com LLDP and port mac/ip tracking. 

Thanks\!

Attached are walk\_snmp results after adding mibs from: 

\*\*\* 3-Com mibs found at:
http://support.3com.com/documents/switches/3CRH3CMIBS/3CRH3CMIBSv2.zip

walk\_snmp results from from a 5500g

Reported by: *anonymous

Original Ticket: [snmp-info/feature-requests/26](https://sourceforge.net/p/snmp-info/feature-requests/26)

**Comment by ollyg** [comment]
I think the MIBs are included since netdisco/netdisco-mibs@de824d815dcb65f44e60984b7948d1e6685b4450 and the 3com support since at least netdisco/snmp-info@ 3b6088f454b5211ea00267fddd45b9a6b3563312
