### ISSUE TITLE
PaloAlto firewalls

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#189]
I have a few of these firewalls and would really want them to be recognized \(I'm using netdot\)

http://www.paloaltonetworks.com/

I can be of assistance with snmp outputs and test unit

Reported by: vendis

Original Ticket: [snmp-info/feature-requests/44](https://sourceforge.net/p/snmp-info/feature-requests/44)

**Comment by ollyg** [comment]
Looks like this was done in 4ea66fc0fd2f4209c08b8a360ac51c1c6b174f84.
