### ISSUE TITLE
New vendor Huawei and Alcatel-lucent Modifications

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#193]
I create a new pm, based on h3c.pm. that can add support to Huawei Datacom Devices (routers and switches). I also made some modifications at Timetra.pm to reflect some routers from Alcatel-lucent. About Huawei: i didn´t find some updated official mibs from huawei, so i compile some products from others Huawei mibs to HUAWEI-MIB to reflect the models i need. I made some tricks to get os version but still need to get serial number from chassis. I´m not a developer so, please check the code for improvements. Feel free to contact me about tests. Thanks.

Reported by: fernando360

Original Ticket: [snmp-info/feature-requests/48](https://sourceforge.net/p/snmp-info/feature-requests/48)

**Comment by ollyg** [comment]
HUAWEI-MIB in netdisco-mibs is already up to date.

**Comment by jeneric** [comment]
Closing as I believe all of the requested/submitted enhancements have been added.
