### ISSUE TITLE
support for powerconnect 8164F

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#196]
i wouldl ike to have support for the powerconnect 8100 series 
i have attached the output of make_snmpdata.pl and MIBS file all together

Reported by: grocanar2

Original Ticket: [snmp-info/feature-requests/51](https://sourceforge.net/p/snmp-info/feature-requests/51)

**Comment by ollyg** [comment]
I have applied a couple of these that were in the Dell vendor directory. The majority are in the netgear directory but look like upstream Broadcom templates and I'm not experienced enough to know whether this is legitimate.

Certainly, two references to BROADCOM-REF-MIB did need changing to NETGEAR-REF-MIB to work, anyway.

**Comment by jeneric** [comment]
MIBs have been updated to better support device model identification. The Dell class has been reworked to better support newer power connect based models based upon the provided snmpwalk in the commit referenced above.
