### ISSUE TITLE
support for TP-Link devices

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#197]
support for TP-Link devices (especially JetStream TL-SG3424) would be welcomed, thanks.

Private MIBs are on vendor's web, but there is none compatible MIBs support for any TP-Link device in the project...

Reported by: marksta

Original Ticket: [snmp-info/feature-requests/52](https://sourceforge.net/p/snmp-info/feature-requests/52)

**Comment by ollyg** [comment]
Closing as there is no info attached.
