### ISSUE TITLE
Add Support for Gigamon devices

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#198]
I'd like to graciously request addition of Gigamon tap/span aggregation devices to SNMP::Info.  We use a lot of these and desire to track them better in NetDisco's inventory, so need support for this vendor added.

I'm uploading the output from make_snmpdata.pl as well as the vendor's MIB.

Please contact me if you need further information.  

Reported by: wan-geek

Original Ticket: [snmp-info/feature-requests/53](https://sourceforge.net/p/snmp-info/feature-requests/53)

**Comment by ollyg** [comment]
MIB in the attachment on this ticket is the same as that already in netdisco-mibs.

**Comment by jeneric** [comment]
Support added in release 3.50
