### ISSUE TITLE
Sidewinder firewall polling

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#201]
Please re-work SNMP::Info as necessary to include Sidewinder firewall polling.  The sidewinder has a few odd behaviors in which fields it supports and which it does not \(see attachment\)

Reported by: delcampc

Original Ticket: [snmp-info/feature-requests/56](https://sourceforge.net/p/snmp-info/feature-requests/56)

**Comment by ollyg** [comment]
Not enough information in the ticket to act.
