### ISSUE TITLE
Support for Aerohive access points

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#202]
Would like to add SNMP::Info module support for Aerohive access points.  I have attached the make_snmpdata.pl output file.

Reported by: dhboyd26-sf

Original Ticket: [snmp-info/feature-requests/57](https://sourceforge.net/p/snmp-info/feature-requests/57)

**Comment by ollyg** [comment]
MIBs for some Aerohive are already there. The bundle on this ticket updated the TRAPS MIB to fix a bunch of errors and it applied well.

**Comment by jeneric** [comment]
Thanks for providing the snmpwalk, a new class has been created to support Aerohive access points and is included in version 3.58.
