### ISSUE TITLE
Support for Nexans Switch devices

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#203]
Please add the Support for Nexans Switch Devices, the mib files are attached.
I also created a ticket at the netdisco thread by mistake! Sorry for that....

Reported by: bobe2x

Original Ticket: [snmp-info/feature-requests/58](https://sourceforge.net/p/snmp-info/feature-requests/58)

**Comment by ollyg** [comment]
The Nexans MIBs submitted are the same version as the ones in netdisco-mibs, so I guess this was done already. Thanks :).
