### ISSUE TITLE
Checkpoint VSX Gaia

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#204]
Hi,

Hi i've a long time issue to solve, is netdisco perform arpnip and macsuck over checkpoint firewall VS GAIA with virtual firewall's, it's only performs it from vs 0(phisical firewall).
netdisco discovery it like snmp layer3 device only, and again only interface info, arp info, mac info from vs 0(phisical firewall).
Can someone help me with this one?

Reported by: ncansado

Original Ticket: [snmp-info/feature-requests/59](https://sourceforge.net/p/snmp-info/feature-requests/59)

**Comment by ollyg** [comment]
Looks like the code from Max Kosmach was merged.
