### ISSUE TITLE
Cisco has changed how c2960X switch modules are presented via SNMP

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#205]
Cisco has changed how c2960X switch modules are presented via SNMP.

If you look under modules in Netdisco it looks like this:

  +Catalyst C29xx Switch Stack (C29xx Stacking) / cevC29xxStack
      + WS-C2960X-24PS-L (1) fw: 15.0(2)EX5 hw: V02 sw: 15.0(2)EX5 [serial: xxxxxxxxxxxxxxx] / cevChassisWsC2960x24psL / WS-C2960X-24PS-L [FRU]

compared to a older switch model:

+  WS-C2960-48TC-L (1) fw: 12.2(58)SE2 hw: V04 sw: 12.2(58)SE2 [serial: xxxxxxxxxxxxx] / cevChassisCat296048 / WS-C2960-48TC-L
    -  WS-C2960-48TC-L - Fan 0 (WS-C2960-48TC-L - Fan 0) / cevFanCat2960CFM22
    +  WS-C2960-48TC-L - Fixed Module 0 (WS-C2960-48TC-L - Fixed Module 0) / cevModuleCat296048

The result is that all different variants of C2960X are grouped under a generic "29xx Stack" model rather than the real model.

Reported by: pecillo

Original Ticket: [snmp-info/feature-requests/60](https://sourceforge.net/p/snmp-info/feature-requests/60)

**Comment by ollyg** [comment]
This is now in our Vendors documentation guide. Add this to your 37xx config:
    no snmp-server sysobjectid type stack-oid
