### ISSUE TITLE
_raw methods not implemented for all subclasses

### ISSUE THREAD

**Issue by ollyg** [netdisco/snmp-info#211]
@abraxxa opened [ticket on RT](https://rt.cpan.org/Ticket/Display.html?id=108611) about this:

"For example in SNMP::Info::Layer3::F5 i_type is overridden but i_type_raw isn't defined.
I'd suggest to test all subclasses for interface conformance or use e.g. Role::Tiny to ensure that."

I replied:

"OK I think I see the misunderstanding here. Because we load the MIB for F5, net-snmp will automatically translate enum values from their integer to the string representation (such as "ethernetCsmacd").

Additionally, SNMP::Info can be implemented with a munge routine to further manipulate the values, but that's not done in this case. The _raw suffix to any method is a hint to avoid this second munge. There is no similar way to avoid the MIB translation of the enum.

So is that what you're seeing? "

**Comment by abraxxa** [comment]
Yes exactly!

**Comment by abraxxa** [comment]
To pick that up after our IRC discussion: _raw means don't do any munging, which SNMP::Info isn't doing in this case, so it's output is correct in this regard BUT when SNMP::Info->new is called with SNMP::Session's UseEnums => 0 parameter the SNMP module doesn't translate the (in the case of ifType) numerical value to a string which the faked implementation in Layer3::F5 ignores.

**Comment by ollyg** [comment]
So this is a fairly narrow scope fix - the "fake" ifType in the F5 module should be rewritten.

**Comment by abraxxa** [comment]
Yes, with the downside that UseEnums is a foreign module parameter.

**Comment by ollyg** [comment]
Fix in commit f9464bc.

**Comment by abraxxa** [comment]
Did you forget to push this commit? Can't find it.

**Comment by ollyg** [comment]
I was travelling and needed to wait for more internet. It's uploaded now: f9464bc

**Comment by abraxxa** [comment]
Great, thanks!
