### ISSUE TITLE
SNMP::Info Device models Genua, ATMedia, Liebert

### ISSUE THREAD

**Issue by ollyg** [netdisco/snmp-info#214]
Original email from Thomas Wollner.

    diff Info.pm Info.pm.dist-3.31
    1571,1573d1570
    <         13458 => 'SNMP::Info::Layer2::ATMedia',
    <         3717  => 'SNMP::Info::Layer3::Genua3',
    1582d1578
    <         476   => 'SNMP::Info::Layer7::Liebert',

[atmedia-mib.tar.gz](https://github.com/netdisco/snmp-info/files/804302/atmedia-mib.tar.gz)
[genua-mib.tar.gz](https://github.com/netdisco/snmp-info/files/804303/genua-mib.tar.gz)
[liebert-mib.tar.gz](https://github.com/netdisco/snmp-info/files/804304/liebert-mib.tar.gz)

[patch.tar.gz](https://github.com/netdisco/snmp-info/files/804308/patch.tar.gz)

**Comment by jeneric** [comment]
The three SNMP::Info classes have been added and should be available in 3.59. The liebert MIBs had previously been included in netdisco-mibs. Objects have been redefined in the Genua MIBs therefore the OIDs were hardcoded in the class. OIDs were hard-coded for atmedia as there was only one MIB file.
