### ISSUE TITLE
Nokia/Alcatel-Lucent 7705 LLDP

### ISSUE THREAD

**Issue by ollyg** [netdisco/snmp-info#215]
_From @netdisco-automation on February 13, 2016 2:0_

The service router from Alcatel-Lucent (now Nokia) does not use standard LLDP MIB and uses TIMETRA-LLDP-MIB.

Attached is the make_snmpdata.pl output,

Reported by: charris54

Original Ticket: [netdisco/netdisco2/263](https://sourceforge.net/p/netdisco/netdisco2/263)

_Copied from original issue: netdisco/netdisco#264_

**Comment by jeneric** [comment]
Thanks for including the snmpwalk output, this helped greatly in adding support which has been added in the commit referenced above. The TIMETRA-LLDP-MIB is also included in the latest release of netdisco-mibs.
