### ISSUE TITLE
Problem with port naming on brocade ICX switches - doesn't appear to use ifName table

### ISSUE THREAD

**Issue by nneul** [netdisco/snmp-info#224]
## Expected Behavior
Interface name should match configuration and ifName table in mib. 
From module I'm getting "GigabitEthernet1/1/1", but the actual name is "ethernet1/1/1", and that is what is returned in the ifName mib as well:

root@itapps-d1:/local/swconf (master)$ snmpwalk -v 2c -c xxxxxx yyyyyyyyy 1.3.6.1.2.1.31.1.1.1.1
IF-MIB::ifName.1 = STRING: ethernet1/1/1
IF-MIB::ifName.2 = STRING: ethernet1/1/2
IF-MIB::ifName.3 = STRING: ethernet1/1/3
...

## Current Behavior
Returning ifDescr in all cases for $obj->interfaces instead of ifName
Same if I use the i_name() access path. I'm not actually seeing any way in code right now to get output of 'ethernet1/1/1'. 

Code is treating the switch as class ...::Foundry 

## Context

Primary impact in my case is I'm needing to correlate LLDP based discovery data with a different system that actually uses the ifName table for identity. 

## Your Environment
* SNMP::Info version used: 3.31 on ubuntu 16.04
* Netdisco version (if used): n/a

  Copyright (c) 1996-2015 Brocade Communications Systems, Inc. All rights reserved.
    UNIT 1: compiled on Feb 18 2016 at 22:55:59 labeled as SPS08030fa
      (28688580 bytes) from Primary SPS08030fa.bin
        SW: Version 08.0.30faT211 
      Compressed Boot-Monitor Image size = 786944, Version:10.1.05T215 (spz10105)
  HW: Stackable ICX7250-48-HPOE
==========================================================================
UNIT 1: SL 1: ICX7250-48P POE 48-port Management Module
      Serial  #:DUK3829M0VT
      License: BASE_SOFT_PACKAGE   (LID: fwmINHOoFxv)
      P-ASIC  0: type B344, rev 01  Chip BCM56344_A0
==========================================================================
UNIT 1: SL 2: ICX7250-SFP-Plus 8-port 80G Module
==========================================================================

**Comment by nneul** [comment]
Note - I'm scanning a few thousand switches of various models from other vendors (mostly cisco) - only seeing this problem (or at least visible impact) on the brocade units.

**Comment by ollyg** [comment]
Hi Nathan,

I believe you can get the field you want using the method `i_name_raw()`. The "_raw" suffix skips SNMP::Info munging the returned data. 

Whether this is a but or not... I'm not sure.

regards,
Oliver.

**Comment by nneul** [comment]
Interesting... on the brocade, that does give the expected value. Strangely, on the cisco switches, i_name_raw returns interface descriptions instead. Either way - it does get me an easy way to retrieve it. Thank you.

**Comment by ollyg** [comment]
Thanks for the follow up and reference. This makes me think we ought to document what should happen for different calls on different platforms, for instance as per http://www.irobert.info/display/IRINFO/Understanding+ifDescr%2C+ifName+and+ifAlias.
