### ISSUE TITLE
Avaya VSP devices - no ifAlias

### ISSUE THREAD

**Issue by ml-cms** [netdisco/snmp-info#226]
On Avaya VSP devices no ifAlias is discovered and displayed in Netdisco.
The problem could be in RapitCity.pm because rcPortName is empty on VSP devices.

## Expected Behavior

ifAlias schold be displayed.

## Possible Solution

For test we change line 74:
'rc_alias'        => 'rcPortName',
in
'rc_alias'        => 'ifAlias',

...but his can break older devices.

## Steps to Reproduce (for bugs)

1. discover a Avaya VSP device
2. look in netdisco on port list
3. ifAlias is empty - only Port Name is displayed like "Port 1/1"
4. 

## Your Environment

* SNMP::Info version used: 3.37
* Netdisco version (if used):

**Comment by Ouacaze** [comment]
Hi,
I just installed netdisco 2.37.5, and have the same issue.
The solution given indeed solves the problem, at least for VSPs.

BTW, thanks to the Netdisco team for their incredible work !

**Comment by jeneric** [comment]
Fix for the issue has been committed as referenced above. It first tries to use 'rcPortName' but if that isn't defined or is an empty string it will now use 'ifAlias' before using the default 'ifName'.
