### ISSUE TITLE
Avaya switch 4950GTS-PWR-PLUS detection wrong.

### ISSUE THREAD

**Issue by zoeloe** [netdisco/snmp-info#239]
## Expected Behavior
Interfaces should be numbered correctly.

## Current Behavior
From a stack with 4 units of 4950GTS-PWR-PLUS, the detected ports in netdisco are numbered:
1.[1-50]
3.[1-50]
5.[1-50]
7.[1-50]

PoE capable ports from units 2 and 4 are not detected ("0" ports detected)

## Your Environment
Switch/Stack: SW version: boss / 7.4.0.009
SNMP::Info version 3.39
App-Netdisco-2.037003

**Comment by zoeloe** [comment]
Suggested intermediate fix:
It seems that a 4950 switch has a index_factor of 128.
It looks that modifying SNMP::Info::Layer2::Baystack.pm

the diff is e.g.:
232c232
<         if ( ( $model =~ /(5[56]\d\d)|VSP|(4950)/ )
---
>         if ( ( $model =~ /(5[56]\d\d)|VSP/ )

does the trick. It would be nice if a generic catch-all fix would be available. A similar regex would catch
other devices with an index_factor of 128.

**Comment by ollyg** [comment]
fixed in 4afbd37, many thanks!!
