### ISSUE TITLE
Unable to arpnip an checkpoint Gai R80.10 Gateway/Firewall

### ISSUE THREAD

**Issue by chatarGit** [netdisco/snmp-info#245]
Hi,
Running a manual arpnip on netdisco dones'nt give any result.
It looks like netdisco can not parse results.

`[netdisco@berger2 ~]$ ~/bin/netdisco-sshcollector -DQ`
`Warning: Permanently added 'X.X.X.X' (RSA) to the list of known hosts.`
`This system is for authorized use only.`
`This system is for authorized use only.`
`[1080] 2018-01-08 13:29:06 debug X.X.X.X 1080 arpnip()`
`[1082] 2018-01-08 13:29:06 debug Y.Y.Y.Y 1082 arpnip()`
`[1080] 2018-01-08 13:30:06  warn WARNING: no entries received from <X.X.X.X>`
`[1082] 2018-01-08 13:30:06  warn WARNING: no entries received from <Y.Y.Y.Y>`
`Can't use string ("1") as an ARRAY ref while "strict refs" in use at /home/netdisco/bin/netdisco-sshcollector line 114, <$__ANONIO__> line 3.`

## Expected Behavior

As described in perl5/lib/perl5/App/Netdisco/SSHCollector/Platform/GAIAEmbedded.pm file, arp result expected is like :
`? (192.168.17.178) at 5C:F9:DD:71:1F:08 [ether] on LAN1`
on gaia, arp result looks like :

`## CurrAddress                  HWtype  HWaddress           Flags Mask            Iface`
`A.B.C.D              ether   00:1C:FF:AA:AE:98   C                     eth1.954`
`XX.YYY.ZZZ.WWW           ether   FF:FF:FF:FF:FF:FF   CM                    eth1.355`

## Patch
Changing regexp in file fix the problem : 
`[root@serv]$ diff /home/netdisco/perl5/lib/perl5/App/Netdisco/SSHCollector/Platform`/GAIAEmbedded.pm.bak /home/netdisco/perl5/lib/perl5/App/Netdisco/SSHCollector/Platform/GAIAEmbedded.pm`
`69c69,70`
`<     my $linereg = qr/\?\s+\(([0-9\.]+)\)\s+at\s+([a-fA-F0-9:]+)/;`
`---`
`>     my $linereg = qr/([0-9\.]+)\s+ether\s+([a-fA-F0-9:]+).+/;`
`> #    my $linereg = qr/\?\s+\(([0-9\.]+)\)\s+at\s+([a-fA-F0-9:]+)/;`

## Environnement Netdisco : 
Built using Open Source
Software 	Version
App::Netdisco 	2.38.5
SNMP::Info 	3.39
DB Schema 	46
PostgreSQL 	8.4.20
Perl 	5.10.1

## Environement Gaia : 
ckp> show version all
Product version Check Point Gaia R80.10
OS build 421
OS kernel version 2.6.18-92cpx86_64
OS edition 64-bit

Hope this helps
Cédric

**Comment by ollyg** [comment]
Hello Cédric, many thanks for the patch! This is now in Netdisco's current release.
