### ISSUE TITLE
LLDP retrieval of Dlink device port returns space compressed data 

### ISSUE THREAD

**Issue by Linwood-F** [netdisco/snmp-info#249]
I have a Cisco 3650 at 192.168.1.1, and a DLink DGS-3120-48PC at 10.162.0.10, connected from Gi1/0/18 to port 41.

When queried on the DLink for the port 41 I see: 

```
$ snmpwalk -v2c -c 1k2hf5c7 10.162.0.10  IF-MIB::ifDescr.41
IF-MIB::ifDescr.41 = STRING: D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1
```

When the Cisco is queried for the LLDP neighbor I see the following (note I looked ahead of time to see it was index 6): 

```
$ snmpwalk -v2c -c 1k2hf5c7 192.168.1.1 1.0.8802.1.1.2.1.4.1.1 | grep -P "\.6\s"
iso.0.8802.1.1.2.1.4.1.1.4.0.18.6 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.5.0.18.6 = Hex-STRING: 84 C9 B2 19 51 68
iso.0.8802.1.1.2.1.4.1.1.6.0.18.6 = INTEGER: 7
iso.0.8802.1.1.2.1.4.1.1.7.0.18.6 = Hex-STRING: 31 2F 34 31 00
iso.0.8802.1.1.2.1.4.1.1.8.0.18.6 = STRING: "D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1"
iso.0.8802.1.1.2.1.4.1.1.9.0.18.6 = STRING: "ETSBH-SW"
iso.0.8802.1.1.2.1.4.1.1.10.0.18.6 = STRING: "Gigabit Ethernet Switch"
iso.0.8802.1.1.2.1.4.1.1.11.0.18.6 = Hex-STRING: 60 00
iso.0.8802.1.1.2.1.4.1.1.12.0.18.6 = Hex-STRING: 60 00
```
Both of the above look correct to me.   How however when I look in Netdisco 

```
select ip, port, remote_ip, remote_port from device_port dp where dp.ip = '192.168.1.1' and remote_port like 'D-Link%'
"192.168.1.1"	"GigabitEthernet1/0/18"	"10.162.0.10"	"D-LinkDGS-3120-48PCR1.02.013Port41onUnit1"

```

Note the lack of spaces in the remote port name.

Something (I presume the SNMP module?) is space-compressing these, but not the other port name, causing a mis-match when comparing a port to remote port.

## Expected Behavior
Same port name -- I think with spaces as that's what is coming from the device,

## Current Behavior
One side (the remote port) is space compressed, the other (port) is not.

## Possible Solution
I think it's best to have the actual port names be used in the associated fields, and if some kind of more flexible comparison is needed to match, that it be done (only) in the comparison, not by munging the data.

## Steps to Reproduce (for bugs)

This would require a DLink (possibly with similar firmware, not clear if this is firmware specific as I have only a few), and a Cisco.  I've tried to provide the actual SNMP results above; I am happy to provide more queries against the devices or database, and/or test patched Netdisco for them.

## Context
Maps do not show links.

## Your Environment
* SNMP::Info version used: 3.49
* Netdisco version (if used):  2.39.15
On Ubuntu Linux 16.04.6.
The Cisco was a 3650 running IOS-XE version 3.07.05E FC1.
The DLink was a DGS-3120-48PC running B1.0.1.1 (likely quite old)

**Comment by JeroenvIS** [comment]
By the way, that data also ends up without spaces in remote_port column on our Netdisco install, so I can confirm that spaces are stripped - but I expect that's somewhere in Netdisco code and not in SNMP::Info layer.
Hilighting @ollyg because he knows that code best.

**Comment by JeroenvIS** [comment]
Thanks, not a ticket against SNMP::Info then, saw that you already created a new one against Netdisco. Perfect.

**Comment by Linwood-F** [comment]
@JeroenvIS no, that ticket is a different issue I think, as relates to which SNMP field is used for comparison, not the truncation.  I'll copy the above into an issue there.

**Comment by JeroenvIS** [comment]
Oh, didn't read close enough then, sorry.
