### ISSUE TITLE
Problem with getting ARP table from Palo Alto devices

### ISSUE THREAD

**Issue by iganchevup8** [netdisco/snmp-info#256]
This is not a netdisco issue, but I need to get a fix with that and part of the solution needs to be done on netdisco, so thanks for considering this request.

Currently Palo Alto devices do not provide access to ARP table via snmp. A trick would be to connect via ssh and to record the output to a file, eventually combined with more information about VLANs and VLAN names.

What would be the way to integrate this information into netdisco in order to have the records into the IP inventory.

Thanks in advance.

* SNMP::Info version used: 3.53
* Netdisco version : 2.39.20

**Comment by jeneric** [comment]
Please try the Palo Alto netdisco  sshcollector module as suggested by @JeroenvIS. I don't believe we can collect this information via SNMP.
