### ISSUE TITLE
update for os_ver() in SNMP::Info::Layer3::AlcateLucent.pm

### ISSUE THREAD

**Issue by stromsoe** [netdisco/snmp-info#271]
Alcatel-Lucent devices return sysDescr in variety of different formats.  A sample from devices that I have access to return:

6.3.1.975.R01 Service Release, June 24, 2008.
6.3.4.378.R01 GA, March 11, 2009.
Alcatel-Lucent 6.4.4.343.R01 GA, June 23, 2011.
Alcatel-Lucent 6.4.4.373.R01 Service Release, August 02, 2011.
Alcatel-Lucent 6400 24 COPPER POE PORTS W/STK 6.4.3.520.R01 GA, April 08, 2010.
Alcatel-Lucent OS6400-48 6.4.5.635.R02 Service Release, June 25, 2015.
Alcatel-Lucent OS6400-P24 6.4.5.402.R02 GA, December 24, 2012.

os_ver() returns "Alcatel-Lucent" for all of the second variety, which isn't accurate.  Replacing the sub with this returns the correct information for me:

```
sub os_ver {
     my $alu = shift;

     my $descr = $alu->description();
     return $1 if $descr =~ m/\b(\d[\.\d]+R\d+) (?:GA|Service Release), /;

     # No clue what this will try but hey
     return $alu->SUPER::os_ver();
}
```

**Comment by ollyg** [comment]
have applied the patch suggested by @stromsoe
