### ISSUE TITLE
MAC not found 

### ISSUE THREAD

**Issue by cecco16** [netdisco/snmp-info#276]
Comparing the mac address table on the switch (Cisco 3750) and Netdisco reports, there are few missing entries.

## Expected Behavior
The information concerning the members of a certain VLAN should be consistent with the mac address table

## Current Behavior
Not all of physical address are present.

## Context
Discovery of Cisco and Juniper switches. The issue is specifically related to a Cisco 3750.

## Your Environment

* SNMP::Info version used:   3.61
* Netdisco version (if used):  2.39.31

**Comment by inphobia** [comment]
we had the same issue, the following fixed it for us:

https://github.com/netdisco/netdisco/issues/227#issuecomment-442276250


to replicate you need to use snmpbulkwalk instead of snmpwalk, if it takes over 3 seconds to get a complete reply you'll hit the standard netdisco snmp timeout.
