### ISSUE TITLE
Netdisco failing to discover Meraki APs

### ISSUE THREAD

**Issue by RobinBeismann** [netdisco/snmp-info#277]
Hello,

we're trying to discover Meraki Access Points.
Discovery using snmpwalk works fine, however netdisco fails.

I'm using the snmpwalk command:
snmpwalk -v3 -a sha -A xyzauthpass -u xyzusername -x des -X xyzprivpass -l authpriv 10.X.X.X

The deployment.yml Part looks like this:
device_auth:
  - tag: AP
    user: xyzusername
    auth:
      pass: xyzauthpass
      proto: SHA
    priv:
      pass: xyzprivpass
      proto: DES
    only:
      - 10.X.X.X/24

I was able to verify that the discover choses the right device credentials with "SHOW_COMMUNITY=1 ~netdisco/bin/netdisco-do discover -d 10.X.X.X -D".

Any idea?
We already successfully discovered around 30 Cisco switches with different credentials.

Thanks!

snmpwalk Output:
`SNMPv2-MIB::sysDescr.0 = STRING: Meraki MR42 Cloud Managed AP
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.29671.2.22
SNMPv2-MIB::sysName.0 = STRING: xxxxx
SNMPv2-MIB::sysORID.1 = OID: SNMPv2-MIB::snmpMIB
SNMPv2-MIB::sysORID.2 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORID.3 = OID: IF-MIB::ifMIB
SNMPv2-MIB::sysORID.4 = OID: iso.2.840.10036
SNMPv2-MIB::sysORDescr.1 = STRING: The MIB module for SNMPv2 entities
SNMPv2-MIB::sysORDescr.2 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORDescr.3 = STRING: The MIB module to describe generic objects for network interface sub-layers
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for managing 802.11 implementations
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.2 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.3 = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysORUpTime.4 = Timeticks: (2) 0:00:00.02
IF-MIB::ifNumber.0 = INTEGER: 4
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifIndex.2 = INTEGER: 2
IF-MIB::ifIndex.3 = INTEGER: 3
IF-MIB::ifDescr.1 = STRING: wired0
IF-MIB::ifDescr.2 = STRING: apr0
IF-MIB::ifDescr.3 = STRING: apr1
IF-MIB::ifType.1 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifType.2 = INTEGER: ieee80211(71)
IF-MIB::ifType.3 = INTEGER: ieee80211(71)
IF-MIB::ifMtu.1 = INTEGER: 0
IF-MIB::ifMtu.2 = INTEGER: 0
IF-MIB::ifMtu.3 = INTEGER: 0
IF-MIB::ifSpeed.1 = Gauge32: 0
IF-MIB::ifSpeed.2 = Gauge32: 0
IF-MIB::ifSpeed.3 = Gauge32: 0
IF-MIB::ifPhysAddress.1 = STRING: xxxx
IF-MIB::ifPhysAddress.2 = STRING: 0:0:0:0:0:0
IF-MIB::ifPhysAddress.3 = STRING: 0:0:0:0:0:0
IF-MIB::ifAdminStatus.1 = INTEGER: up(1)
IF-MIB::ifAdminStatus.2 = INTEGER: up(1)
IF-MIB::ifAdminStatus.3 = INTEGER: up(1)
IF-MIB::ifOperStatus.1 = INTEGER: up(1)
IF-MIB::ifOperStatus.2 = INTEGER: up(1)
IF-MIB::ifOperStatus.3 = INTEGER: up(1)
IF-MIB::ifLastChange.1 = Timeticks: (0) 0:00:00.00
IF-MIB::ifLastChange.2 = Timeticks: (0) 0:00:00.00
IF-MIB::ifLastChange.3 = Timeticks: (0) 0:00:00.00
IF-MIB::ifInOctets.1 = Counter32: 60625814
IF-MIB::ifInOctets.2 = Counter32: 5623132
IF-MIB::ifInOctets.3 = Counter32: 159920657
IF-MIB::ifInUcastPkts.1 = Counter32: 104077738
IF-MIB::ifInUcastPkts.2 = Counter32: 21988
IF-MIB::ifInUcastPkts.3 = Counter32: 1850318
IF-MIB::ifInNUcastPkts.1 = Counter32: 0
IF-MIB::ifInNUcastPkts.2 = Counter32: 0
IF-MIB::ifInNUcastPkts.3 = Counter32: 0
IF-MIB::ifInDiscards.1 = Counter32: 12
IF-MIB::ifInDiscards.2 = Counter32: 0
IF-MIB::ifInDiscards.3 = Counter32: 0
IF-MIB::ifInErrors.1 = Counter32: 0
IF-MIB::ifInErrors.2 = Counter32: 3088
IF-MIB::ifInErrors.3 = Counter32: 39803
IF-MIB::ifOutOctets.1 = Counter32: 821446122
IF-MIB::ifOutOctets.2 = Counter32: 16296374
IF-MIB::ifOutOctets.3 = Counter32: 3255939026
IF-MIB::ifOutUcastPkts.1 = Counter32: 5688995
IF-MIB::ifOutUcastPkts.2 = Counter32: 75955
IF-MIB::ifOutUcastPkts.3 = Counter32: 5867918
IF-MIB::ifOutNUcastPkts.1 = Counter32: 0
IF-MIB::ifOutNUcastPkts.2 = Counter32: 0
IF-MIB::ifOutNUcastPkts.3 = Counter32: 0
IF-MIB::ifOutDiscards.1 = Counter32: 0
IF-MIB::ifOutDiscards.2 = Counter32: 0
IF-MIB::ifOutDiscards.3 = Counter32: 0
IF-MIB::ifOutErrors.1 = Counter32: 0
IF-MIB::ifOutErrors.2 = Counter32: 251
IF-MIB::ifOutErrors.3 = Counter32: 247
IF-MIB::ifOutQLen.1 = Gauge32: 0
IF-MIB::ifOutQLen.2 = Gauge32: 0
IF-MIB::ifOutQLen.3 = Gauge32: 0
IF-MIB::ifSpecific.1 = OID: SNMPv2-SMI::zeroDotZero
IF-MIB::ifSpecific.2 = OID: SNMPv2-SMI::zeroDotZero
IF-MIB::ifSpecific.3 = OID: SNMPv2-SMI::zeroDotZero
IF-MIB::ifName.1 = STRING: wired0
IF-MIB::ifName.2 = STRING: apr0
IF-MIB::ifName.3 = STRING: apr1
IF-MIB::ifInMulticastPkts.1 = Counter32: 0
IF-MIB::ifInMulticastPkts.2 = Counter32: 0
IF-MIB::ifInMulticastPkts.3 = Counter32: 0
IF-MIB::ifInBroadcastPkts.1 = Counter32: 0
IF-MIB::ifInBroadcastPkts.2 = Counter32: 0
IF-MIB::ifInBroadcastPkts.3 = Counter32: 0
IF-MIB::ifOutMulticastPkts.1 = Counter32: 0
IF-MIB::ifOutMulticastPkts.2 = Counter32: 0
IF-MIB::ifOutMulticastPkts.3 = Counter32: 0
IF-MIB::ifOutBroadcastPkts.1 = Counter32: 0
IF-MIB::ifOutBroadcastPkts.2 = Counter32: 0
IF-MIB::ifOutBroadcastPkts.3 = Counter32: 0
IF-MIB::ifHCInOctets.1 = Counter64: 17240506056
IF-MIB::ifHCInOctets.2 = Counter64: 5623132
IF-MIB::ifHCInOctets.3 = Counter64: 159920657
IF-MIB::ifHCInUcastPkts.1 = Counter64: 104077802
IF-MIB::ifHCInUcastPkts.2 = Counter64: 21988
IF-MIB::ifHCInUcastPkts.3 = Counter64: 1850318
IF-MIB::ifHCInMulticastPkts.1 = Counter64: 0
IF-MIB::ifHCInMulticastPkts.2 = Counter64: 0
IF-MIB::ifHCInMulticastPkts.3 = Counter64: 0
IF-MIB::ifHCInBroadcastPkts.1 = Counter64: 0
IF-MIB::ifHCInBroadcastPkts.2 = Counter64: 0
IF-MIB::ifHCInBroadcastPkts.3 = Counter64: 0
IF-MIB::ifHCOutOctets.1 = Counter64: 821456710
IF-MIB::ifHCOutOctets.2 = Counter64: 16296374
IF-MIB::ifHCOutOctets.3 = Counter64: 3255939026
IF-MIB::ifHCOutUcastPkts.1 = Counter64: 5689053
IF-MIB::ifHCOutUcastPkts.2 = Counter64: 75955
IF-MIB::ifHCOutUcastPkts.3 = Counter64: 5867918
IF-MIB::ifHCOutMulticastPkts.1 = Counter64: 0
IF-MIB::ifHCOutMulticastPkts.2 = Counter64: 0
IF-MIB::ifHCOutMulticastPkts.3 = Counter64: 0
IF-MIB::ifHCOutBroadcastPkts.1 = Counter64: 0
IF-MIB::ifHCOutBroadcastPkts.2 = Counter64: 0
IF-MIB::ifHCOutBroadcastPkts.3 = Counter64: 0
IF-MIB::ifHighSpeed.1 = Gauge32: 0
IF-MIB::ifHighSpeed.2 = Gauge32: 0
IF-MIB::ifHighSpeed.3 = Gauge32: 0
IF-MIB::ifAlias.1 = STRING:
IF-MIB::ifAlias.2 = STRING:
IF-MIB::ifAlias.3 = STRING:
IF-MIB::ifAlias.3 = No more variables left in this MIB View (It is past the end of the MIB tree)
`
Netdisco discover:
`[netdisco@XXXXXXXXX ~]$ INFO_TRACE=1 ~netdisco/bin/netdisco-do discover -d 10.X.X.X -D
[2412] 2018-10-24 08:23:51  info App::Netdisco version 2.039031 loaded.
[2412] 2018-10-24 08:23:54  info discover: [10.X.X.X] started at Wed Oct 24 10:23:54 2018
[2412] 2018-10-24 08:23:54 debug discover: running with timeout 600s
[2412] 2018-10-24 08:23:54 debug => running workers for phase: check
[2412] 2018-10-24 08:23:54 debug -> run worker check/_base_/0
[2412] 2018-10-24 08:23:54 debug Discover is able to run.
[2412] 2018-10-24 08:23:54 debug => running workers for phase: early
[2412] 2018-10-24 08:23:54 debug -> run worker early/properties/100
[2412] 2018-10-24 08:23:54 debug snmp reader cache warm: [10.X.X.X]
[2412] 2018-10-24 08:23:54 debug [10.X.X.X:161] try_connect with ver: 3, class: SNMP::Info, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global(uptime) NOSUCHOBJECT at /home/netdisco/perl5/lib/perl5/App/Netdisco/Transport/SNMP.pm line 239.
[2412] 2018-10-24 08:23:58 debug discover failed: could not SNMP connect to 10.X.X.X
[2412] 2018-10-24 08:23:58 debug -> run worker early/properties/100
[2412] 2018-10-24 08:23:58 debug -> run worker early/properties/100
[2412] 2018-10-24 08:23:58 debug -> run worker early/properties/100
[2412] 2018-10-24 08:23:58 debug => running workers for phase: main
[2412] 2018-10-24 08:23:58 debug -> run worker main/canonicalip/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/entities/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/neighbors/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/neighbors/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/portpower/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/portproperties/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/vlans/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/wireless/100
[2412] 2018-10-24 08:23:58 debug -> run worker main/withnodes/0
[2412] 2018-10-24 08:23:58  info discover: finished at Wed Oct 24 10:23:58 2018
[2412] 2018-10-24 08:23:58  info discover: status defer: discover failed: could not SNMP connect to 10.X.X.X
`

Best regards
Robin

**Comment by inphobia** [comment]
seems netdisco cant connect to the device for some reason if i read the logs correctly: "08:23:58 info discover: status defer: discover failed: could not SNMP connect to 10.X.X.X "
could it be the meraki device does not provide sysuptimeinstance? what does an snmpget of oid .1.3.6.1.2.1.1.3.0 give?

another option could be that you have multiple snmp v3 tags, according to https://github.com/netdisco/netdisco/wiki/Configuration#device_auth : 
"When configuring multiple SNMPv3 stanza please use only and/or no ACLs for each, otherwise only the first stanza is ever used (this is a limitation in the underlying SNMP library)." is the subnet specified in "only:" correct?

**Comment by JeroenvIS** [comment]
FWIW: last time I worked with a Meraki (for a customer of $prev_employer), I was amazed how limited and (IMHO) non-conforming their SNMP implementation was. Indeed the APs didn't provide sysUpTime when I worked with them, nor did they provide sysServices. They are not compliant with SNMPv2-MIB specs, they only implement a subset.

I'd file a bug (or "leave a wish", or whatever they call it in their portal) to have Meraki at least implement SNMPv2-MIB::sysUpTime.0 (.1.3.6.1.2.1.1.3.0).

**Comment by maxslug** [comment]
I can confirm this.  I tried to get some Meraki gear (Router + Switch + APs)  to play w/ Netdisco a few months ago and found that the SNMP support was not sufficient. 

To confound things there are two ways of getting SNMP data : from the local device, and from the cloud provider / management system.   Even if you could aggregate the two, it doesn't have what we need.

**Comment by RobinBeismann** [comment]
You're right, they don't supply the SNMPv2-MIB::sysUpTime.0 (.1.3.6.1.2.1.1.3.0) value, this is why the snmp lib refuses to scan them. 
I guess I'll fill a feature request there.

Thanks for the help, you can close this issue then.
