### ISSUE TITLE
missing licenses

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#289]
while this might not be relevant, the following files are missing their license & author:

Layer2/3Com.pm
Layer2/Adtran.pm
Layer2/Ubiquiti.pm
Layer3/DLink.pm

perhaps this is not needed and they are assumed to use the snmp::info project license. then again you could ask why all the other modules have the license explicitly included.

## Your Environment

* SNMP::Info version used: master

**Comment by ollyg** [comment]
Thanks, fixed in:
[master 81004615] #289 add BSD licence to files where missing

**Comment by inphobia** [comment]
"Copyright (c) **2019**"

almost.... 😄
