### ISSUE TITLE
snmp::info should show full class used (_load_attr too)

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#294]
when using `netdisco-do show -d xxxx -e function` it would be handy if the class that was used for a function could be shown.

for example:
```
netdisco-do show -d 10.40.254.112 -DI -e interfaces
[24002] 2019-01-12 00:18:21  info App::Netdisco version 2.040002 loaded.
[24002] 2019-01-12 00:18:21  info show: [10.40.254.112]/interfaces started at Sat Jan 12 01:18:21 2019
[24002] 2019-01-12 00:18:21 debug show: running with timeout 600s
[24002] 2019-01-12 00:18:21 debug => running workers for phase: check
[24002] 2019-01-12 00:18:21 debug -> run worker check/_base_/0
[24002] 2019-01-12 00:18:21 debug Show is able to run
[24002] 2019-01-12 00:18:21 debug => running workers for phase: main
[24002] 2019-01-12 00:18:21 debug -> run worker main/_base_/100
[24002] 2019-01-12 00:18:21 debug snmp reader cache warm: [10.40.254.112]
[24002] 2019-01-12 00:18:21 debug [10.40.254.112:161] try_connect with ver: 2, class: SNMP::Info::Layer3::C6500, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.64
SNMP::Info::device_type() layers:00000110 id:9 sysDescr:"Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.0(2)SE6, RELEASE SOFTWARE (fc2) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2014 by Cisco Systems, Inc. Compiled Wed 09-Apr-14 02:55 by prod_rel_team"
SNMP::Info::_load_attr i_index : IF-MIB::ifIndex : .1.3.6.1.2.1.2.2.1.1
SNMP::Info::_load_attr i_description : IF-MIB::ifDescr : .1.3.6.1.2.1.2.2.1.2
```

nowhere is it shown which class the interfaces function comes from (in this case it's from snmp::info::layer3), but it could also have been from snmp::info base or any other place. it would be nice if this was added to the debug output.

for the _load_attr debug lines it would also be handy if you would know from which class they came, in case they were overwritten.

## Expected Behavior

provide more useful debug output.

## Current Behavior

need to go through snmp::info modules to try & find out which class a function came from.

## Possible Solution

debug mode should show which class a function comes from, also _load_attr should provide this too.

## Steps to Reproduce (for bugs)

1. netdisco-do show -d ip_addr -e interfaces
2. try to figure out which interfaces function was used.

## Context

i was trying to figure out why my portchannels either showed no members or wrong members. (for layer3::nexus & layer3::c6500). it took me some time to find out that interfaces was overridden in snmp::info::layer3.

also see: netdisco/netdisco#486

## Your Environment

* SNMP::Info version used: HEAD
* Netdisco version (if used): HEAD

**Comment by inphobia** [comment]
side note, using netdisco-do -II (more snmp::info debugging) also does not provide the used classes.

**Comment by inphobia** [comment]
SNMP::Info::MRO provides this functionality and more, but having some option in either snmp::info or netdisco-do to show the full class would be more userfriendly.

i'll fix up the documentation for mro and perhaps add a wiki page on what & how it does it's thing.

**Comment by ollyg** [comment]
Showing the actual class where a method comes from originally is tricky to do with the current design of SNMP::Info, as the Exporter use means all methods are sort-of defined everywhere.

Anyway, with the following patch, if Debug is set greater than 1, then at least the list of classes checked is shown in order in the debug log output:
[master c8f686b7] #294 snmp::info should show full class used

e.g.
```
SNMP::Info::Layer3::NetSNMP has resolution order:
  SNMP::Info::Layer3::NetSNMP
  SNMP::Info::LLDP
  SNMP::Info
  Exporter
  SNMP::Info::Layer3
  SNMP::Info::PowerEthernet
  SNMP::Info::IPv6
  SNMP::Info::Entity
  SNMP::Info::EtherLike
  SNMP::Info::Bridge
  SNMP::Info::AdslLine
  SNMP::Info::DocsisHE
```
