### ISSUE TITLE
perl 5.28 removal of "use vars"

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#297]
https://metacpan.org/pod/distribution/perl/pod/perldelta.pod#Removal-of-use-vars

it seems `"use vars"` has been deprecated from perl 5.28. "use vars" is used in most snmp::info modules, so this most likely will need to be addresses. 

## Possible Solution

`our` is the proposed solution to change `"use vars"` too.

i tested a few modules i'm familiar with like layer2::aerohive & layer2::ciscosb, which seem to be ok after using "our" instead of "use var", but more testing is required.

**Comment by ollyg** [comment]
thanks! after gratuitous use of sed, we now have:
[master 39f6592d] #297 perl 5.28 removal of "use vars"
