### ISSUE TITLE
need mac munge type for sun format using colons

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#301]
i seem to be running into the following problem a lot lately:
a device reports mac address in sun type (- seperated without leading zeroes) but instead of using dashes it uses colons to seperate entries.

example:
CISCOSB-DEVICEPARAMS-MIB::rndBasePhysicalAddress.0 = STRING: `68:bc:c:75:b:c9`
notice how the 3rd item is `c` instead of `0c` and the 5th is `b` not `0b`.

(example of sun format, also drops leading zeros: `0-c0-7a-4-6-8b`)

## Expected Behavior

have a way to import this non standard but commonly used format.

## Current Behavior

need to write a conversion for this format for each device where it's used.

## Possible Solution

i'm wondering we should add a few more common munge functions to the main info.pm instead of defining them in different modules.

## Steps to Reproduce (for bugs)

1. try to add mac address entry to ciscosb device detail page
2. find out it's in this oid: `CISCOSB-DEVICEPARAMS-MIB::rndBasePhysicalAddress.0 = STRING: 68:bc:c:75:b:c9`
3. then come to the realization that this is not a common mac format
4. write a conversion function in ciscosb or try to get one included in a more base module.

## Context

when trying to expand snmp::info i don't want to copy functions all over the place. common sense & best practices are that functions shared in multiple modules get inherited instead of copied.

## Your Device

* Vendor: cisco
* Device Model: SRW224G4P-K9
* Operating System Version: 1.4.9.4
* Snmpwalk output of .1.3.6.1.2.1.1:

> SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.6.1.82.24.2
> DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (651670300) 75 days, 10:11:43.00
> SNMPv2-MIB::sysContact.0 = STRING:
> SNMPv2-MIB::sysName.0 = STRING: D10-SMB-01
> SNMPv2-MIB::sysLocation.0 = STRING: d10
> SNMPv2-MIB::sysServices.0 = INTEGER: 2
> SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORID.1 = OID: SNMPv2-SMI::enterprises.89.73
> SNMPv2-MIB::sysORDescr.1 = STRING: RS capabilities
> SNMPv2-MIB::sysORUpTime.1 = Timeticks: (0) 0:00:00.00

## Your Environment

* SNMP::Info version used: 2.04.03
* Netdisco version (if used): 3.64

tagging @postilion too since i think he wrote ciscosb support.

**Comment by ollyg** [comment]
Hi @inphobia, I would use the [NetAddr::MAC](https://metacpan.org/pod/NetAddr::MAC) distribution.

OK, some would argue that SNMP::Info should have minimal dependencies. However if we're starting to get MAC addresses in STRING values which are all over the shop, then we should definitely farm out this work to NetAddr::MAC in my opinion.

I'll close this ticket, with the assumption you'll add something like this to the code (and a `Build.PL` dependency on `NetAddr::MAC`):

```perl
use NetAddr::MAC;
my $tmp_mac = NetAddr::MAC->new(
  mac => $info->rndBasePhysicalAddress,
  die_on_error => 0,
);
my $mac = (($tmp_mac and not $tmp_mac->errstr) ? $tmp_mac->as_ieee : '');
```
