### ISSUE TITLE
improve duplicate interfaces() fixup

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#320]
background info in netdisco/netdisco#554

layer2.pm & layer3.pm both have logic for making sure interfaces() does not return duplicate values, which helps a lot to make snmp::info work out of the box. i do see a few possible improvements however.

## Current Behavior

1. the first duplicate found will not have it's iid appended. it would be more consistant if the first duplicate could also have it's iid added.
2. interfaces() has no guarantee of returning consistent data in the case of doubles. since hashes and keys() do not have a fixed order of returning items (as far as i know), the first interface being tagged as duplicate can change on each run.

for the case i'm using to test i have a device which returns blank ifDescr for 35 of it's 60 interfaces, however the one without it's iid added changes on every run. here are 4 runs of the same device (`netdisco-do show -d 10.40.254.26 -e interfaces`). output trimmed to relevant data.
```
    1    " (1)",
    2    "Management",
    3    " (3)",
    4    "",
    5    " (5)",
    6    " (6)",
```

```
    51   " (51)",
    52   " (52)",
    53   "",
    54   " (54)",
    55   " (55)",
    56   " (56)",
    57   " (57)",
    58   " (58)"
```

```
    51   " (51)",
    52   " (52)",
    53   " (53)",
    54   " (54)",
    55   " (55)",
    56   "",
    57   " (57)",
    58   " (58)"
```

```
    51   " (51)",
    52   " (52)",
    53   " (53)",
    54   "",
    55   " (55)",
    56   " (56)",
    57   " (57)",
    58   " (58)"
```

as you can see the interface without iid added changes on each run.

## Possible Solution

i think adding iid to each duplicate, including the first one, would make the output a lot more consistent. while ifIndex can change (and can do so frequently certain types of interfaces), i still think the end result will be a more stable interfaces() output as having it change with each run.

## Steps to Reproduce (for bugs)

have a device with duplicate interface names (ciscosb & fortinet without their fixups) and run interfaces() a few times.

## Your Device

* Vendor: fortinet & ciscosb without fixups to interfaces()

## Your Environment

* SNMP::Info version used: 3.66
* Netdisco version (if used): 2.42.3

also tagging @postilion , @jeneric , @ollyg & @maxslug you all had this discussion before.

**Comment by ollyg** [comment]
thanks! fixed in: [master ea9ad92c] #320 improve duplicate interfaces() fixup
