### ISSUE TITLE
shadowing of variable in layer2/3.pm

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#330]
https://github.com/netdisco/snmp-info/blob/2c61248016f657ecb08cbc4640d6121d6768aafe/lib/SNMP/Info/Layer3.pm#L335-L338

https://github.com/netdisco/snmp-info/blob/2c61248016f657ecb08cbc4640d6121d6768aafe/lib/SNMP/Info/Layer2.pm#L150-L153

is there a reason to define $port again with `my` in both examples here? according to https://perldoc.perl.org/perlsub.html#Private-Variables-via-my() it's valid syntax:
```
my $x = $x;
can be used to initialize a new $x with the value of the old $x
```

but i can't for the life of me figure out why.

thx

**Comment by ollyg** [comment]
surprised it doesn't blow up with redefinition error. the second my should be removed so it's just updating `$port`.

**Comment by ollyg** [comment]
Thanks, fixed in
[master 6341ad15] #330 fix redefine of port variable
