### ISSUE TITLE
missing defined check in info.pm

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#332]
just making a note here so i don't forget. at least the downtime of demo.snmplabs.com is doing more as just erroring our travis tests :)

```
xt/10_remote_snmplabs.t ..... SNMP::Info::_global(layers) Timeout at xt/10_remote_snmplabs.t line 14.
SNMP::Info::_global(description) Timeout at xt/10_remote_snmplabs.t line 14.
SNMP::Info::specify() - Could not get info from device at xt/10_remote_snmplabs.t line 14.
Can't call method "debug" on an undefined value at /home/testdisc/src/snmp-info/blib/lib/SNMP/Info.pm line 1399.
xt/10_remote_snmplabs.t ..... Dubious, test returned 2 (wstat 512, 0x200)

```

https://github.com/netdisco/snmp-info/blob/254bfd11a312038d78d432a765a488ab48f9afda/lib/SNMP/Info.pm#L1391-L1397

perhaps something like
`if ( defined $info and ($info->debug() > 1) ) {`
could work?

**Comment by ollyg** [comment]
Thanks, fixed in
[master 23d11551] #332 fix undef error when debug on $info
