### ISSUE TITLE
UBNT EdgeMAX version reporting

### ISSUE THREAD

**Issue by LBegnaud** [netdisco/snmp-info#349]
I sent an email to the mailing list, but got no response. Going to go ahead and open this issue to tag my PR onto.

UBNT EdgeSwitch has a bootcode version that is updated separately from the firmware, so I'm suggesting we add this to the version string

Also, UBNT likes to tag a lot of sub versions per hardware model that makes the netdisco Inventory screen unclean when many things are there:

![image](https://user-images.githubusercontent.com/15981748/61974585-7ee9d480-afac-11e9-8337-2951a3a4e112.png)

This would also return only the first 3 groups of the firmware:

`EdgeOS v1.10.9.5166937.190213.1810`

would be reported as

`v1.10.9`

Edgeswith example to add bootcode:

`EdgeSwitch 48-Port 500W, 1.8.1.5145168, Linux 3.6.5-1b505fb7, 1.1.0.5102011` 

and report it as

`1.8.1.-b1.1.0`

**Comment by LBegnaud** [comment]
fyi also decided to cleanup airos version reporting in the same manor (reduce useless values)

**Comment by inphobia** [comment]
cool, i like the idea. but would it be an option to truncate the os version like you're doing now but leave the other info either in the description field or modules tab? like for this cisco; simple os version but all other info still available:

![image](https://user-images.githubusercontent.com/39005454/62587604-0267c780-b8c3-11e9-8c97-34259e88a36c.png)

![image](https://user-images.githubusercontent.com/39005454/62587683-58d50600-b8c3-11e9-9f27-53da87ff098b.png)
somewhat truncated but you get the idea.

you can still query it all via custom reports:
https://github.com/netdisco/netdisco/wiki/Configuration#reports

**Comment by LBegnaud** [comment]
yea i like the idea. I'll update to append the missing information to the description. Examples of what it looks like currently for each model type are below. I'll simply put a space (or would we prefer a newline?) on the description and add the data that i've pared down:

![image](https://user-images.githubusercontent.com/15981748/62630174-0c55ee80-b8f4-11e9-8a89-86101797e5e7.png)

![image](https://user-images.githubusercontent.com/15981748/62630192-1841b080-b8f4-11e9-8f75-e7b4b205cf50.png)

![image](https://user-images.githubusercontent.com/15981748/62630227-2394dc00-b8f4-11e9-8dff-17e232381bf7.png)

**Comment by inphobia** [comment]
@LBegnaud unrelated to this issue, but since you are the main man behind our docker support, i was wondering if you have some time to spare to have a look at the open issues/pull requests there and perhaps point me in the right direction to get a few of them fixed (been getting quite some docker issues lately so i guess our docs could use some polish).

thx

**Comment by LBegnaud** [comment]
well i started the ball rolling but olly really took the reins and rebuilt everything there... I do like the path he took but it just means i'm not really familiar with the inner workings of most of that architecture.

All that being said, i'll take a glance and see what i can help with

**Comment by inphobia** [comment]
i tried to leave comments about what i got stuck on in the issue tracker, but gave up after a while and then did https://github.com/netdisco/netdisco-docker/pull/19
which to me was clearer as a docker noob to get working, so i wonder if the stuff i wrote made sense :)

**Comment by LBegnaud** [comment]
i really question the need to have two separate docker-compose files. Using local volumes should work for any purposes. It's really kind of a hack to expose local folders directly and manipulate them while the container is running. Much easier to load the netdisco-do container and link it to a local volume than to shared folders.

In general your changes here are pretty substantial, can you help me out and give a rough TL;DR ? Best i can tell these are probably just changes we should make for the generic instructions as well.
