### ISSUE TITLE
No is_master, slave_of discovered on Cisco N5k

### ISSUE THREAD

**Issue by rc9000** [netdisco/snmp-info#379]
Hi guys

I noticed that apparently none of our N5k properly show the master/slave relationship of port-channels. I've seen #296 which supposedly addresses this issue (thanks @inphobia), but still no luck even AFAICT it's included in SNMP::Info 3.68 we're using here. E.g. I have: 

    show port-channel summary:   Po1(SU)     Eth      LACP      Eth1/1(P)    Eth1/17(P)  

    interface port-channel1
      description VPC Peer-Link  cptza-x508-2
      switchport mode trunk
      spanning-tree port type network
      vpc peer-link
    
    interface Ethernet1/1
      description VPC Peer-Link  cptza-x508-2, e1/1
      switchport mode trunk
      channel-group 1 mode active
    
    interface Ethernet1/17
      description VPC Peer-Link  cptza-x508-2, e1/17
      switchport mode trunk
      channel-group 1 mode active

after a discovery, there is none of this to be seen:

    select port, is_master, is_uplink, slave_of from device_port where ip = 'x.x.x.x' and port in ('Ethernet1/17', 'Ethernet1/1', 'port-channel1')

	
    [
      {
        "port": "Ethernet1/1",
        "is_master": false,
        "is_uplink": null,
        "slave_of": null
      },
      {
        "port": "Ethernet1/17",
        "is_master": false,
        "is_uplink": null,
        "slave_of": null
      },
      {
        "port": "port-channel1",
        "is_master": false,
        "is_uplink": null,
        "slave_of": null
      }
    ]]

netdisco-do show -d x.x.x.x -e agg_ports just gives: 
...
SNMP::Info 3.68
SNMP::Info::device_type() layers:01000110 id:9 sysDescr:"Cisco NX-OS(tm) n5000, Software (n5000-uk9), Version 5.2(1)N1(9), RELEASE SOFTWARE Copyright (c) 2002-2011 by Cisco Systems, Inc. Device Manager Version 6.1(1),  Compiled 4/28/2015 7:00:00"
SNMP::Info::_load_attr pagpGroupIfIndex : CISCO-PAGP-MIB::pagpGroupIfIndex : .1.3.6.1.4.1.9.9.98.1.1.1.1.8
SNMP::Info::_load_attr dot3adAggPortSelectedAggID : IEEE8023-LAG-MIB::dot3adAggPortSelectedAggID : .1.2.840.10006.300.43.1.2.1.1.12
SNMP::Info::_load_attr lag_members : CISCO-LAG-MIB::clagAggPortListInterfaceIndexList : .1.3.6.1.4.1.9.9.225.1.4.1.1.2
\ {}
[27858] 2019-12-13 19:43:07  info show: finished at Fri Dec 13 20:43:07 2019
[27858] 2019-12-13 19:43:07  info show: status done: Showed agg_ports response from x.x.x.x

It looks like all of these _load_attr come up empty, both with `netdisco-do show -e` or when using snmpwalk directly, using V2 without any views or other restrictions.
Anybody has this working successfully on N5k, or any ideas what's going wrong here?

**Comment by rc9000** [comment]
Ok please don't invest time in this, it turns out that IEEE8023-LAG-MIB with dot3adAggPortSelectedAggID and friends is only supported from 6.0(2)N2(1) onwards. I have the impression I've also seen issues like this on N5k with NX-OS 7.x, but I'm not sure if we had a recent enough SNMP::Info there. I'll check and report back.

**Comment by inphobia** [comment]
hm, #296 should also support cisco's own CISCO-LAG-MIB, which is supported since 4.2(1)N1(1) according to ftp://ftp.cisco.com/pub/mibs/supportlists/nexus5000/Nexus5000MIBSupportList.html

pagp/lacp requires the ports to be online & the aggregation proto to be in sync before ports show up in the pagp/8023 mibs on cisco iirc. cisco-lag-mib just shows everything, including static channels & fex uplinks, so i wouldn't focus to much on IEEE8023-LAG-MIB.

could you check if snmpwalk returns anything for .1.3.6.1.4.1.9.9.225.1.4.1.1.1 (CISCO-LAG-MIB::clagAggPortListPorts) or .1.3.6.1.4.1.9.9.225.1.4.1.1.2 (CISCO-LAG-MIB::clagAggPortListInterfaceIndexList)?

https://github.com/netdisco/snmp-info/issues/295#issuecomment-453715569 mentions that @JeroenvIS tested this on his n5k's, dunno nx-os version. my n5k's are unracked & powered down, if you want i can try & get 'em running again. they were on some nx-os 5.x version.

**Comment by rc9000** [comment]
Ok I finally got around to test the latest releases on the NX-OS 7 environment, and now it works perfectly:

    -[ RECORD 1 ]------------
    port      | Ethernet1/1
    is_master | f
    slave_of  | port-channel1
    is_uplink | t
    -[ RECORD 2 ]------------
    port      | Ethernet1/2
    is_master | f
    slave_of  | port-channel1
    is_uplink | t
    -[ RECORD 3 ]------------
    port      | port-channel1
    is_master | t
    slave_of  |
    is_uplink | t

Many thanks for this patch @inphobia !
I'll currently not investigate the NX-OS 5 behavior further since it's not a priority and EOL soon, but thanks for the hints.
