### ISSUE TITLE
Netdisco Issue - SNMP Could Not Connect

### ISSUE THREAD

**Issue by patchmau5** [netdisco/snmp-info#381]
Hi all,

I've had Netdisco working on site for about 5-6 months without any issue. But it looks like it's now stopped inventorying devices - and I'm not well versed with Linux or Netdisco to know how to resolve this!

I've attached a screenshot of the error I receive when attempting to do a discover, which is how I originally inventoried the system. The omitted info is the IP of our Core Switch.\

I'm not too familiar with Linux systems, so unsure of how to provide the output of snmpwalk, but will return to provide if I can figure it out.

![Netdisco_Screenshot_Error](https://user-images.githubusercontent.com/59613287/71904226-a6e58280-315d-11ea-96d7-9ab8877126fb.jpg)

Netdisco has been installed on an Ubuntu 18.04.3 VM, using the instructions provided here:
https://metacpan.org/pod/App::Netdisco

System info as taken from the homepage of Netdisco.

App::Netdisco 2.44.4
SNMP::Info	 3.70
DB Schema	 61
PostgreSQL	 10.00.10
Perl	                 5.26.1

Any advice appreciated!

**Comment by dsm-team** [comment]
can you run a snmpwalk toward this host ?

**Comment by patchmau5** [comment]
> can you run a snmpwalk toward this host ?
> just snmpwalk -v2c -cpublic ip_of_host

Thanks for the reply!

I did as advised and just get:
`Timeout: No Response from x.x.x.x`

I've also tried with -v1, -v3 to the same end.

Thank you.

**Comment by dsm-team** [comment]
Then try the same command on another host and if there is no result as well it means that it's either an issue on the snmp or firewall on the remote device or a network issue if you are on different subnet (firewall, routing)

**Comment by patchmau5** [comment]
Thanks. I'll have a go and report back.

**Comment by dsm-team** [comment]
BTW (obviously) 'public' in the snmp walk should be your snmpcommunity :)
Also check if your remote device has ip restrictions on the snmp requests.

**Comment by patchmau5** [comment]
OK. I'm off to read about snmp communities then!

**Comment by patchmau5** [comment]
I checked the SNMP Community of our Core Switch and it had in fact changed. We had a third-party perform some work on our systems and this must have been something they changed. Apologies for not noting this before my post went up.

I updated the yml and performed the discovery again, and the Core Switch now picks up. However it's neighbours, and cascading devices, are not registering.

If I head over to Netdisco's web interface I can see there is a long list of queued checks to the neighbouring switches, but they aren't progressing. Their SNMP Community is the same as the CS, so now I'm stuck again. Why isn't this filtering down?

Thank you.

**Comment by dsm-team** [comment]
Try to run a manual netdisco-do to discover the device that are stuck in netdisco and restart the netdisco server as well might help

**Comment by patchmau5** [comment]
I ran another ~/bin/netdisco-do -D discover -d x.x.x.x and whilst it pumped out a whole heap of info, it still didn't populate the database beyond the CS. I then rebooted the server and reattempted to the same outcome.

The Netdisco system is so brilliantly simple, but I feel like I must need to change something else in the yml. Is there anything I'm missing?

**Comment by patchmau5** [comment]
![Screenshot_2020-01-13_at_14_21_37](https://user-images.githubusercontent.com/59613287/72334716-b3b22b00-36b5-11ea-9627-ca3f58da74ac.jpg)

Here's the snmpwalk that the forum template asks for.

**Comment by patchmau5** [comment]
I still haven't had any luck beyond it discovering our Core Switch with a targeted request (~/netdisco-do discover -d x.x.x.x). In the past this would navigate through our network and pick up all our other switches, but not it spends about 30 seconds on the target before completion.

My brief research (googling!) has moved toward it being an LLDP/CDP problem. I can't however see anywhere in the yml to configure anything with regards to this.

Any further help would be appreciated.

**Comment by inphobia** [comment]
> I updated the yml and performed the discovery again, and the Core Switch now picks up. However it's neighbours, and cascading devices, are not registering.
> 
> If I head over to Netdisco's web interface I can see there is a long list of queued checks to the neighbouring switches, but they aren't progressing. Their SNMP Community is the same as the CS, so now I'm stuck again. Why isn't this filtering down?

could be this: https://github.com/netdisco/netdisco/wiki/Troubleshooting#change-the-snmp-community-string-for-a-device 

if not then `netdisco-do discover -D -d x.x.x.x` would help us out (notice the extra _-D_).

**Comment by patchmau5** [comment]
Thanks inphobia.

I followed the link and can confirm that the target's original SNMP string was removed, and two new strings were added. These changes were made across our network, so when the old string was removed the two new were deployed to all our switching devices. They all match.

I've since updated the yml and the new Read-Only SNMP string matches the target and all other branching devices' Read-Only string.

I've attached the output of the above command.
[netdisco-do_github.txt](https://github.com/netdisco/snmp-info/files/4121471/netdisco-do_github.txt)

I'm at a loss! Thanks again.

**Comment by patchmau5** [comment]
Just to add to this, as I came back to this today, it still doesn't work. I'm not sure where I'm going wrong. An article I read mentioned that if the SNMP Community Strings change then it's worthwhile removing any devices in case a bad string is cached, and then to reattempt.

So I did just that, removed the only switch it discovered, the core switch, and ran it again - which is what we did on setup and it all worked perfectly. So I SSH'd onto the Netdisco server and ran:

`~/bin/netdisco-do D discover -d x.x.x.x`

Then I hopped onto the web frontend after 10-15 minutes and can see the below in the Job Queue, showing nothing but queued jobs from 11:18 today. Can anyone diagnose from this what could be causing this? It's very frustrating, I expect to find a very small problem causing this but can't figure it out from the documentation what I've got wrong!

![Screenshot_2020-02-25_at_11_32_06](https://user-images.githubusercontent.com/59613287/75244014-df4f2780-57c2-11ea-96d8-1493525994d3.jpg)

**Comment by patchmau5** [comment]
Closed - I'm an idiot; IP of the NetDisco server needed adding to the IP Authorised Management Addresses on each switch in the network, a change actioned by a third-party contractor whose work I was not aware of. Took some digging and dedicated sitting down. Thanks to all involved who helped.
