### ISSUE TITLE
SNMP discovery problems with Dell S5148F-ON

### ISSUE THREAD

**Issue by heiko-ma** [netdisco/snmp-info#390]
## Expected Behavior
After the device was discovered, it should resolve the neighbor devices using the lldp statistics. As this device has layer2 to layer4 capabilities, those should be displayed in the **detail** section

## Current Behavior

The device is discovered with Layer 4 and 7 capabilities so that the features **arpnip** and **macsuck** are not usable (this is because of the wrong layers). Therefore, the device cannot discover its neighbors because it can't use the mac-address table or the arp table. I think this is due to the fact that snmp-info reads out the wrong device data.
The screenshot can be found below:
![image](https://user-images.githubusercontent.com/64192965/80187479-fe760400-860f-11ea-8a7d-2b1450de5ffb.png)

## Steps to Reproduce (for bugs)

1. Open the netdisco web-gui
2. Enter the FQDN of the device you want to discover
3. After the device was discovered, click on the details and review the settings of the device

## Context

I'm trying to build a map of our company network. Since the Dell S51484F-ON is our Core-Switch Model, the discovery of this devices is very vital for us.

## Your Device

* Vendor: Dell EMC
* Device Model: S5148F-ON
* Operating System Version: 10.4.3.1
* Snmpwalk output of .1.3.6.1.2.1.1:

> SNMPv2-MIB::sysDescr.0 = STRING: Dell EMC Networking OS10-Enterprise.
> Copyright (c) 1999-2019 by Dell Inc. All Rights Reserved.
> System Description: OS10 Enterprise.
> OS Version: 10.4.3.1.
> System Type: S5148F-ON
> SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.674.11000.5000.100.2.1.13
> DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (194895693) 22 days, 13:22:36.93
> SNMPv2-MIB::sysContact.0 = STRING: 
> SNMPv2-MIB::sysName.0 = STRING: 
> SNMPv2-MIB::sysLocation.0 = STRING: 
> SNMPv2-MIB::sysServices.0 = INTEGER: 72
> SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORID.1 = OID: SNMPv2-MIB::snmpMIB
> SNMPv2-MIB::sysORID.2 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
> SNMPv2-MIB::sysORID.3 = OID: TCP-MIB::tcpMIB
> SNMPv2-MIB::sysORID.4 = OID: IP-MIB::ip
> SNMPv2-MIB::sysORID.5 = OID: UDP-MIB::udpMIB
> SNMPv2-MIB::sysORID.6 = OID: SNMP-MPD-MIB::snmpMPDCompliance
> SNMPv2-MIB::sysORID.7 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
> SNMPv2-MIB::sysORID.8 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
> SNMPv2-MIB::sysORID.9 = OID: SNMP-NOTIFICATION-MIB::snmpNotifyFullCompliance
> SNMPv2-MIB::sysORDescr.1 = STRING: The MIB module for SNMPv2 entities
> SNMPv2-MIB::sysORDescr.2 = STRING: View-based Access Control Model for SNMP.
> SNMPv2-MIB::sysORDescr.3 = STRING: The MIB module for managing TCP implementations
> SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for managing IP and ICMP implementations
> SNMPv2-MIB::sysORDescr.5 = STRING: The MIB module for managing UDP implementations
> SNMPv2-MIB::sysORDescr.6 = STRING: The MIB for Message Processing and Dispatching.
> SNMPv2-MIB::sysORDescr.7 = STRING: The management information definitions for the SNMP User-based Security Model.
> SNMPv2-MIB::sysORDescr.8 = STRING: The SNMP Management Architecture MIB.
> SNMPv2-MIB::sysORDescr.9 = STRING: The MIB modules for managing SNMP Notification, plus filtering.
> SNMPv2-MIB::sysORUpTime.1 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.2 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.3 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.4 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.5 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.6 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.7 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.8 = Timeticks: (0) 0:00:00.00
> SNMPv2-MIB::sysORUpTime.9 = Timeticks: (0) 0:00:00.00

## Your Environment

* SNMP::Info version used: 3.70
* Netdisco version (if used): 2.45.2
* Operating System: CentOS 7
* Perl Version: 5.16.3
* PostgreSQL Version: 9.2.24

**Comment by inphobia** [comment]
if at all possible we could use this info toe further investigate:
https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#get-snmp-datadump

**Comment by heiko-ma** [comment]
I think my issue is already being handled in #340 . Because we just deployed netdisco as a test-instance I'm afraid I don't have the machine available any more, so getting those infos for you would prove very difficult.
