### ISSUE TITLE
[Airespace] e_class returns non-numeric values

### ISSUE THREAD

**Issue by abraxxa** [netdisco/snmp-info#391]
## Expected Behavior

$snmpinfo->e_class should return the numeric identifiers as the ENTITY-MIB defines for entPhysicalClass.

## Current Behavior

The strings `chassis` and `ap` are returned.
According to the MIB, easily viewable at https://snmp.cloudapps.cisco.com/Support/SNMP/do/BrowseOID.do?objectInput=entPhysicalClass&translate=Translate&submitValue=SUBMIT, the correct value for `chassis` would be 3, what should be used for an access-point is questionable, module (9) or other (1) would be my favorites.

## Possible Solution

Return the numbers instead of the string to conform with the e_class return values of other classes.

## Steps to Reproduce (for bugs)

1. call $snmpinfo->e_class for a Cisco Wireless LAN Controller (WLC) and dump it's ouput

## Your Device

* Vendor: Cisco
* Device Model: AIR-CT5508-K9
* Operating System Version: 8.3.150.0
* Snmpwalk output of .1.3.6.1.2.1.1:
```
iso.3.6.1.2.1.1.1.0 = STRING: "Cisco Controller"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.9.1.1069
iso.3.6.1.2.1.1.3.0 = Timeticks: (849867390) 98 days, 8:44:33.90
iso.3.6.1.2.1.1.4.0 = STRING: "removed"
iso.3.6.1.2.1.1.5.0 = STRING: "fqdn"
iso.3.6.1.2.1.1.6.0 = STRING: "snmplocation"
iso.3.6.1.2.1.1.7.0 = INTEGER: 2
```

## Your Environment

* SNMP::Info version used: 3.70
* Netdisco version (if used): none

**Comment by JeroenvIS** [comment]
@abraxxa By design, SNMP::Info will provide translated outputs where possible. Indeed the Airespace class has code that will build an ENTITY-MIB like structure, which returns textual values for chassis and AP.
However, that's fully in line with other SNMP::Info classes: with the right MIBs loaded, dumping "e_class" will also give textual values.

Example output for one of our routers:

```
[188395] 2020-07-22 08:55:33  info show: [x.x.x.x]/e_class started at Wed Jul 22 10:55:33 2020
\ {
    1      "chassis",
    2      "container",
    3      "backplane",
    4      "sensor",
    5      "sensor",
    6      "container",
    7      "fan",
    8      "sensor",
    9      "container",
    10     "container",
    11     "powerSupply",
    12     "sensor",
    13     "sensor",
    14     "sensor",
    17     "sensor",
    18     "sensor",
    24     "container",
    25     "powerSupply",
<snipped>

```
