### ISSUE TITLE
DLink OID sysServices ( .1.3.6.1.2.1.1.7) = "01001000" 

### ISSUE THREAD

**Issue by atretyakov** [netdisco/snmp-info#401]
Hello,
some d-link switches -DES-1210-28/ME, DGS-1210-28/ME etc indicates OID sysServices ( .1.3.6.1.2.1.1.7) = "01001000".

 ~/bin/netdisco-do show  -d des1210-28me-51-3 -e layers
[137115] 2019-01-28 08:53:33  info App::Netdisco version 2.040003 loaded.
[137115] 2019-01-28 08:53:33  info show: [10.0.10.44]/layers started at Mon Jan 28 11:53:33 2019
"01001000"

Therefore, netdisco does not collect level 2 and 3 information . What to do ?

**Comment by JeroenvIS** [comment]
I'd be fine with a small change in SNMP::Info::Layer3::DLink to always report layers 2 & 3; I've worked with DLink devices for a while and never saw a model that couldn't do at least some basic L2 & L3.

A more elegant approach than "always report these layers" could be to actually test a common L2 method (eg `dot1dBaseNumPorts`) and return L2 capability if that method is implemented.

**Comment by ollyg** [comment]
added fix in commit 0e75c44c (needs testing) 

this is in line with first easier suggestion by @JeroenvIS to simply always report 2+3
