### ISSUE TITLE
Dell Aruba Controller MIB Issues

### ISSUE THREAD

**Issue by Trent-Curtis** [netdisco/snmp-info#403]
## Expected Behavior
Discovery of Dell PowerConnect W-7210 Controller-US should discover using SNMP::Info::Layer3::Aruba

## Current Behavior
The discovery process is flip flopping between Dell(SNMP::Info::Layer3::Dell) and Aruba(SNMP::Info::Layer3::Aruba)

## Possible Solution
Hard set model to use SNMP::Info::Layer3::Aruba

## Steps to Reproduce (for bugs)

1. Discover the device:  `~/bin/netdisco-do discover -d 10.16.90.6 -DI`
2. Watch Debug logs to notice flip flop. 

## Your Environment

* Netdisco version used: 2.46.2

**Comment by inphobia** [comment]
it seems the device reports layer3 but needs a specific override to not be classified as a dell switch.

this seems to fix the issue:
https://github.com/netdisco/snmp-info/commit/a85f58207584cd7d8359083dfee343eeedc9fe40

no idea if this generates regressions on other dell gear

**Comment by JeroenvIS** [comment]
> no idea if this generates regressions on other dell gear

I don't expect regressions on other gear (Dell or any other) when only matching on "ArubaOS" in the sysDescr. The "AirOS" match has a higher risk of causing unwanted device class changes.

**Comment by inphobia** [comment]
snmp::info currently has a fallback for layer3::aruba when no layers are detected.

i guess since newer versions report layer3 we can just match on "ArubaOS" & ditch "AirOS". chances are stuff that identifies itself as airos won't have layers() support anyway. i'll adjust the patch.

**Comment by inphobia** [comment]
changed in https://github.com/netdisco/snmp-info/tree/inphobia-patch-1 , also started new changelog for the next release.

**Comment by inphobia** [comment]
reminder for myself : #411 also touches os name, in this case being for ubiquiti.

perhaps a more foolproof detection method is needed if using os().
