### ISSUE TITLE
how to handle mergers (extreme bought foundry / brocade)

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#405]
## Expected Behavior

it seems extreme networks has bought foundry & brocade. at least the ethernet part.

since i got this snmprec privately i can only show certain parts:
![image](https://user-images.githubusercontent.com/39005454/97374179-08770900-18b8-11eb-9289-10af5d78573f.png)

## Current Behavior

 * vendor should be "extreme networks", or based on version of operating system
 * os should be named "ExtremeNetwork OS" (preferably lowercase :) ) according to https://documentation.extremenetworks.com/networkos/HW/vdx6740-installguide.pdf
 * the "version" number has a trailing dot, this should be removed imo.

## Possible Solution

not sure, either just change everything to extreme networks parlé or use the os version to determine os/vendor name.

(side note, extreme also bought aerohive, so same issues might apply there)

according to wikipedia extreme actually owns all of the following:
"Therefore, through a series of historical and contemporary merger and acquisition activity, Extreme Network claims an industry lineage that includes, at a minimum, the networking-focused elements of the following companies: Digital, Chantry, Siemens, Cabletron, Enterasys, AirDefense, Symbol, Motorola, Zebra, Wellfleet, SynOptics, Bay Networks, Nortel Networks, Avaya, Vistapointe, StackStorm, Foundry Networks, and Brocade."
https://en.wikipedia.org/wiki/Extreme_Networks

## Context
since this is common practice perhaps some guidelines on how to cope with snmp::info modules & mergers could be of help?

## Your Environment

* SNMP::Info version used: 3.70

**Comment by inphobia** [comment]
perhaps remotely related:
https://github.com/netdisco/snmp-info/issues/399
https://github.com/netdisco/snmp-info/issues/356

**Comment by JeroenvIS** [comment]
In general: when it comes to device brand, model names and name of the OS, I prefer to be conservative with changes. Either use what the device reports itself (possibly in conjunction with translation through MIBs), or stick with the commonly known / original values.

Specific example: Layer3::H3C does its best to honour the brand and OS that the device reports. This class supports both H3C branded switches and HP branded switches that run Comware, ie that come from the H3C acquisition.
