### ISSUE TITLE
Cisco C4500-X VSS

### ISSUE THREAD

**Issue by DavidLiedke** [netdisco/snmp-info#408]
Netdisco didn´t show the interfaces from a Cisco C4500-X VSS Cluster

![TeamViewer_2020-10-29_20-57-42](https://user-images.githubusercontent.com/25581728/97626124-b229d780-1a29-11eb-999b-566418e9adf3.png)
![TeamViewer_2020-10-29_20-58-56](https://user-images.githubusercontent.com/25581728/97626128-b35b0480-1a29-11eb-8d9b-8bd9b6be3155.png)
![TeamViewer_2020-10-29_20-59-06](https://user-images.githubusercontent.com/25581728/97626130-b3f39b00-1a29-11eb-8c02-5b7b64a5584b.png)

**Comment by inphobia** [comment]
has this ever worked?

layer3::c4000 mostly has support for older c4000 (not c4500) switches running ios.

layer3::c6500 seems to have at least the basics of vss support. we are talking about vss as in the virtual chassis thingy, not stacking like in the 3750 series, right?

**Comment by DavidLiedke** [comment]
No, it has never worked before.

Yes we are talking about VSS (Virtual Chassis) and not about the classic switch stacking (3750,... ). 

I already had a working 6500 VSS in another installation.

**Comment by inphobia** [comment]
the quickest way to test this would be to change:
https://github.com/netdisco/snmp-info/blob/e2544129bcafc594a2a35d5d7fc6b52ef95d6f64/lib/SNMP/Info.pm#L1806
to
`SNMP::Info::Layer3::C6500`

best to also delete the device in netdisco & rediscover it.

if this at least gives some more information i'll make a  better patch that doesn't break older 4000/4500 series.

**Comment by DavidLiedke** [comment]
Nothing changed :/

![0437DE78-C2CA-433D-97DC-E8E5E1800924](https://user-images.githubusercontent.com/25581728/97668010-6440be00-1a81-11eb-80a5-30f3c575e3c7.png)

**Comment by DavidLiedke** [comment]
Is there anything else I can try out ?

**Comment by inphobia** [comment]
other than sending me an snmprec output & pushing me to keep it on my todo list i'm afraid i don't see any options.

for snmprec info see:
https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#get-snmp-datadump

we also mention snmpwalk output but that often introduces strange issues. privacy questions are also addressed in that article.

**Comment by DavidLiedke** [comment]
After a firmware update on the switch with the newest netdisco-mibs package the interfaces are displayed.

**Comment by inphobia** [comment]
> After a firmware update on the switch with the newest netdisco-mibs package the interfaces are displayed.

just as a back reference: with ios-xe 3.09.00 you had issues but the newer version of ios-xe (and updated netdisco-mibs) fixed this. which version of ios-xe are you running now?

**Comment by DavidLiedke** [comment]
The latest netdisco-mibs version with ios-xe version 3.09.00 had unfortunately brought no improvement.

Only after updating to ios-xe 3.11.04 all information incl. interfaces were read out from the switch.

I had to downgrade again shortly after, but that had other reasons. 
But I had the switch freshly read shortly after the upgrade. And received all the information.
