### ISSUE TITLE
move to travis-ci.com

### ISSUE THREAD

**Issue by inphobia** [netdisco/snmp-info#423]
just like netdisco, snmp::info needs to migrate from travis-ci.org to travis-ci.com

**Comment by JeroenvIS** [comment]
Don't know how this integration works, so unassigned myself.

**Comment by inphobia** [comment]
seems you could do this via github as well:
https://github.com/inphobia/Alien-SNMP-MIBDEV/tree/testing/.github/workflows

however this is just a simple build, snmp::info needs to download mibs and some other interactions...

**Comment by inphobia** [comment]
moved to github actions
