### ISSUE TITLE
Feature Request: lldpLocChassisId

### ISSUE THREAD

**Issue by smalllatency** [netdisco/snmp-info#461]
Hi,
do you think it would be possible to add lldpLocChassisId? 
It would be handy to have it directly accessible like: $lldp->lldp_sysname(), etc...

Regards, Marco Barbieri.

**Comment by rc9000** [comment]
I was just poking around in SNMP::Info anyways so I gave this a shot. I still don't full understand what I'm doing so maybe @ollyg and @JeroenvIS make sure to give this a look first :)
