### ISSUE TITLE
Cisco subinterfaces with different vlan encapsulation have wrong vlan ID

### ISSUE THREAD

**Issue by juergen991** [netdisco/snmp-info#468]
If the interface name differs from the VLAN ID netdisco assigns a wrong VLAN ID.

Example:
Search for VLAN 3344
Netdisco finds many devices.
Problem: 
VLAN 3344 does not exist. VLAN 1122 exists and is shown as VLAN 3344.

Detail:
Cisco Router ASR1002HX Configuration:
interface GigabitEthernet0/0/2.3344
 encapsulation dot1Q 1122

Netdisco seems to identify the VLAN ID based on the interface name. The interface name doesn't necessarily need to be the same as the VLAN ID (encapsulation dot1Q ...).

**Comment by ollyg** [comment]
Hi @juergen991 thanks for your patience, and the shared snapshot which was essential to my work. I've applied a patch to SNMP::Info and released (version 3.86). In a couple of hours you should be able to do this to update, then rediscover devices to see the fix:

`~/bin/localenv cpanm --notest SNMP::Info`

**Comment by juergen991** [comment]
Thank you @ollyg ! All VLANs are listed now. Thanks a lot!
