### ISSUE TITLE
update Layer2::Aerohive for the new models

### ISSUE THREAD

**Issue by ollyg** [netdisco/snmp-info#493]
@inphobia reported this

**Comment by inphobia** [comment]
and he will soon start working on it now i have finally migrated to new servers :)

**Comment by inphobia** [comment]
https://github.com/inphobia/snmp-info/tree/nn_extrahives

todo
- [x] use aerohive mibs where possible
- [ ] get rid of ghost interfaces
- [ ] update test suite to account for these changes

under consideration
* update model() parser for newer devices
   * is this needed? newer models can get this via the aerohive mib & older models which don't support the oid work fine with the current parser
* update aerohive mibs
  * aka: where has extreme hidden these files on their support site

**Comment by inphobia** [comment]
done: e20cab97e05ef6345486e576e1954d3f19ff2f69
