### ISSUE TITLE
Silverpeak devices

### ISSUE THREAD

**Issue by alcatron** [netdisco/snmp-info#524]
I see the MIBS are added for silverpeak, but its still not detecting them and comes up as "unknown enterprises" etc.

Is there any cmd i can pass through to see what its actually doing on the device and how its parsing the mib?

### Discussed in https://github.com/netdisco/netdisco/discussions/879

<div type='discussions-op-text'>

<sup>Originally posted by **alcatron** June 14, 2022</sup>
Is there any chance to update the MIBS or support for silverpeak devices? Starting to see some of these for SD-WAN..

Vendor / Model	unknown / enterprises.23867.1.2.0

Description	Silver Peak Systems, Inc. ECSP Linux 4.19.87-sps netdisco/netdisco#1 SMP PREEMPT Thu Dec 9 20:04:39 UTC 2021 ECOS 9.0.5.2_90055 netdisco/netdisco#1-dev 2022-03-07 14:50:12 x86_64 sptest@yocto-app-build7:unknown

Ports/Connected nodes doesnt detect anything also.</div>

**Comment by JeroenvIS** [comment]
The MIBs will only be loaded when they are referenced by a device class. As far as I can see, there is no SNMP::Info class for Silverpeak yet. Now the MIBs have been added, someone could start creating an SNMP::Info class for these devices with the basic stuff, like reporting vendor, model, OS version etc.

**Comment by inphobia** [comment]
either they didn't update the "last-updated" part of their mibs (silverpeak) or the mibs are ancient (circa 2012). 

since your device has a firmware date that mentions 2021 the mibs we added might not be relevant.

snmp::info's main manpage has info on how to write a module, but it might not be very intuitive. made a writeup of how to at least build the basics here:
https://github.com/netdisco/netdisco-mibs/issues/212

**Comment by alcatron** [comment]
Hey, ive been working on this a bit but still havent been able to make it work fully.

Here is what i have done, i made a SilverPeak.pm file and updated to the latest mibs 9.5 attached which need to be updated in the mibs for netdisco.

```
package SNMP::Info::Layer3::SilverPeak;

use strict;
use warnings;
use Exporter;
use SNMP::Info::Layer3;

our @ISA = qw/SNMP::Info::Layer3 Exporter/;
our @EXPORT_OK = qw//;

# SilverPeak specific MIBs
our %MIBS = (
    'SILVERPEAK-MGMT-MIB' => '1.3.6.1.4.1.23867.3',
    'SILVERPEAK-PRODUCTS-MIB' => '1.3.6.1.4.1.23867.1',
);

our %FUNCS = ();

our %GLOBALS = (
    'spsSystemVersion' => '1.3.6.1.4.1.23867.3.1.1.1.1.0',
    'spsProductModel' => '1.3.6.1.4.1.23867.3.1.1.1.2.0',
    'spsSystemSerial' => '1.3.6.1.4.1.23867.3.1.1.1.6.0',
    'spsSystemUptime' => '1.3.6.1.4.1.23867.3.1.1.1.5.0',
);

our %MUNGE = ();

sub layers {
    return '01001100'; # Indicating Layer 3 and 2 capabilities
}

sub vendor {
    return 'silverpeak';
}

sub os {
    return 'silverpeak';
}

sub os_ver {
    my $self = shift;
    return $self->spsSystemVersion();
}

sub model {
    my $self = shift;
    return $self->spsProductModel();
}

sub serial {
    my $self = shift;
    return $self->spsSystemSerial();
}

sub uptime {
    my $self = shift;
    return $self->spsSystemUptime();
}

1;

```

Also have a test script to test the mibs, just as a test.pl file to run

```
#!/usr/bin/perl

use strict;
use warnings;
use SNMP::Info::Layer3::SilverPeak;

my $device = new SNMP::Info::Layer3::SilverPeak(
    AutoSpecify => 1,
    Debug       => 1,
    DestHost    => '10.16.5.1',
    Community   => 'xxxx',
    Version     => 2
) or die "Can't connect to device.\n";

my $class = $device->class();
print "SNMP::Info version: ", $SNMP::Info::VERSION, "\n";
print "Device Type ID: ", $device->id(), "\n";
print "System Description: ", $device->description(), "\n";
print "System Version: ", $device->spsSystemVersion(), "\n";
print "Product Model: ", $device->spsProductModel(), "\n";
print "System Serial: ", $device->spsSystemSerial(), "\n";
print "System Uptime: ", $device->spsSystemUptime(), "\n";

```

I edited the netdisco users ./bashrc file and added the following 

```
export PERL5LIB=/home/netdisco/perl5/lib/perl5:$PERL5LIB
export MIBDIRS=/home/netdisco/netdisco-mibs/silver-peak:/home/netdisco/netdisco-mibs/rfc:/home/netdisco/netdisco-mibs/cisco:/usr/share/snmp/mibs
```

Running the test script returns the following :

```
$ ./test.pl
SNMP::Info::_validate_autoload_method(description) Unable to resolve method.
SNMP::Info::_validate_autoload_method(id) Unable to resolve method.
SNMP::Info 3.970001
SNMP::Info::device_type() layers:01001100 id:undef sysDescr:"undef"
SNMP::Info::specify() - Changed Class to SNMP::Info::Layer3.
SNMP::Info version: 3.970001
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
Device Type ID: .1.3.6.1.4.1.23867.1.2.59
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
System Description: Silver Peak Systems, Inc. EC10104 Linux test-hostname 4.19.87-sps #1 SMP PREEMPT Sat Apr 8 03:24:48 UTC 2023 ECOS 9.2.5.0_94689 #1-dev 2023-06-15 10:55:27 x86_64 sptest@yocto-app-build6:unknown
SNMP::Info::_global spsSystemVersion : SILVERPEAK-MGMT-MIB::spsSystemVersion.0 : .1.3.6.1.4.1.23867.3.1.1.1.1.0
System Version: 9.2.5.0_94689
SNMP::Info::_global spsProductModel : SILVERPEAK-MGMT-MIB::spsProductModel.0 : .1.3.6.1.4.1.23867.3.1.1.1.2.0
Product Model: EC10104
SNMP::Info::_global spsSystemSerial : SILVERPEAK-MGMT-MIB::spsSystemSerial.0 : .1.3.6.1.4.1.23867.3.1.1.1.6.0
System Serial: 00-1B-BC-2F-3F-90
SNMP::Info::_global spsSystemUptime : SILVERPEAK-MGMT-MIB::spsSystemUptime.0 : .1.3.6.1.4.1.23867.3.1.1.1.5.0
System Uptime: 683315865

```

So once i made the Silverpeak.pm and the test script netdisco isnt still picking up the silverpeak device correct product/system, i feel i am missing something to append for it to be able to pickup these values.

I feel i am almost there to get it operational it just needs a slight tweaking, anyone can assist?

[mibs-9.5.zip](https://github.com/user-attachments/files/16327192/mibs-9.5.zip)

**Comment by JeroenvIS** [comment]
Hi Muris, you're setting `AutoSpecify => 1` in your test.pl; try setting `AutoSpecify => 0`.
With AutoSpecify set to 1, you're telling SNMP::Info to determine the correct subclass; however, as far as I can tell from your post, you have not made any changes to SNMP::Info that would lead to it knowing about the Silverpeak subclass.

**Comment by alcatron** [comment]
I found i needed to make changes to Info.pm

/home/netdisco/perl5/lib/perl5/SNMP/Info.pm

So i have added the following -

```
=item SNMP::Info::Layer3::SilverPeak

# SilverPeak
        $objtype = 'SNMP::Info::Layer3::SilverPeak'
            if ( $soid =~ /^\.?1\.3\.6\.1\.4\.1\.23867/ );
```
Even with this added i still cant get it to work properly for the silverpeak Layer 3 class with this script using relying on SNMP Info, it just gets "NO SUCH OBJECT"

```

#!/usr/bin/perl

use strict;
use warnings;
use SNMP::Info;

$ENV{'MIBDIRS'} = '/home/netdisco/netdisco-mibs/silver-peak:/home/netdisco/netdisco-mibs/rfc:/home/netdisco/netdisco-mib$

my $device = '10.16.5.1';
my $community = 'xxxx';

my $info = new SNMP::Info(
    AutoSpecify => 1,
    Debug       => 1,
    DestHost    => $device,
    Community   => $community,
    Version     => 2
);

die "Unable to connect to device.\n" unless defined $info;

my $class = $info->class();
print "Using device sub class: $class\n";

my $description = $info->description() || 'N/A';
my $system_version = $info->spsSystemVersion() || 'N/A';
my $product_model = $info->spsProductModel() || 'N/A';
my $system_serial = $info->spsSystemSerial() || 'N/A';
my $system_uptime = $info->spsSystemUptime() || 'N/A';
```
```
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.970001
SNMP::Info::device_type() layers:01001100 id:23867 sysDescr:"Silver Peak Systems, Inc. EC10104 Linux hrhms037-karo-eth 4.19.87-sps #1 SMP PREEMPT Sat Apr 8 03:24:48 UTC 2023 ECOS 9.2.5.0_94689 #1-dev 2023-06-15 10:55:27 x86_64 sptest@yocto-app-build6:unknown"
SNMP::Info::specify() - Changed Class to SNMP::Info::Layer3::SilverPeak.
Using device sub class: SNMP::Info::Layer3::SilverPeak
SNMP::Info::_validate_autoload_method(description) Unable to resolve method.
SNMP::Info::_global spsSystemVersion : SILVERPEAK-MGMT-MIB::spsSystemVersion.0 : 1.3.6.1.4.1.23867.3.1.1.1.1.0
SNMP::Info::_global(spsSystemVersion) NOSUCHOBJECT at ./test15.pl line 26.
SNMP::Info::_global spsProductModel : SILVERPEAK-MGMT-MIB::spsProductModel.0 : 1.3.6.1.4.1.23867.3.1.1.1.2.0
SNMP::Info::_global(spsProductModel) NOSUCHOBJECT at ./test15.pl line 27.
SNMP::Info::_global spsSystemSerial : SILVERPEAK-MGMT-MIB::spsSystemSerial.0 : 1.3.6.1.4.1.23867.3.1.1.1.6.0
SNMP::Info::_global(spsSystemSerial) NOSUCHOBJECT at ./test15.pl line 28.
SNMP::Info::_global spsSystemUptime : SILVERPEAK-MGMT-MIB::spsSystemUptime.0 : 1.3.6.1.4.1.23867.3.1.1.1.5.0
SNMP::Info::_global(spsSystemUptime) NOSUCHOBJECT at ./test15.pl line 29.
System Description: N/A
System Version: N/A
Product Model: N/A
System Serial: N/A
System Uptime: N/A
```

But if i do direct queries on those OIDS using SNMP Info Layer 3 it returns results

```
SNMP::Info::_validate_autoload_method(description) Unable to resolve method.
SNMP::Info::_validate_autoload_method(id) Unable to resolve method.
SNMP::Info 3.970001
SNMP::Info::device_type() layers:01001100 id:undef sysDescr:"undef"
SNMP::Info::specify() - Changed Class to SNMP::Info::Layer3.
SNMP::Info version: 3.970001
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
Device Type ID: .1.3.6.1.4.1.23867.1.2.59
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
System Description: Silver Peak Systems, Inc. EC10104 Linux hrhms037-karo-eth 4.19.87-sps #1 SMP PREEMPT Sat Apr 8 03:24:48 UTC 2023 ECOS 9.2.5.0_94689 #1-dev 2023-06-15 10:55:27 x86_64 sptest@yocto-app-build6:unknown
SNMP::Info::_global spsSystemVersion : SILVERPEAK-MGMT-MIB::spsSystemVersion.0 : .1.3.6.1.4.1.23867.3.1.1.1.1.0
System Version: 9.2.5.0_94689
SNMP::Info::_global spsProductModel : SILVERPEAK-MGMT-MIB::spsProductModel.0 : .1.3.6.1.4.1.23867.3.1.1.1.2.0
Product Model: EC10104
SNMP::Info::_global spsSystemSerial : SILVERPEAK-MGMT-MIB::spsSystemSerial.0 : .1.3.6.1.4.1.23867.3.1.1.1.6.0
System Serial: 00-1B-BC-2F-3F-90
SNMP::Info::_global spsSystemUptime : SILVERPEAK-MGMT-MIB::spsSystemUptime.0 : .1.3.6.1.4.1.23867.3.1.1.1.5.0
System Uptime: 685503846
```

So what else am i missing?

**Comment by alcatron** [comment]
It did partly work somehow, because netdisco picks up the model now as "spsECSP" obviously its wrong and it should be "EC10104" as per above but its not doing that some reason with the Silverpeak layer3 subclass when i try use it.

![image](https://github.com/user-attachments/assets/d6101ecc-7fa3-4d48-be2d-e7ae91392550)

**Comment by JeroenvIS** [comment]
Your edit to SNMP::Info looks good (although not all context is present to check it fully) and now AutoSpecify appears to work.

I can't explain the result that you're getting from Netdisco yet; based on your code, I would expect the vendor to be updated to 'silverpeak' and the model to match the model from your test code.

**Comment by alcatron** [comment]
alright, so youre not sure why its returning from its own specific sub-class this error-
SNMP::Info::_global spsProductModel : SILVERPEAK-MGMT-MIB::spsProductModel.0 : 1.3.6.1.4.1.23867.3.1.1.1.2.0
SNMP::Info::_global(spsProductModel) NOSUCHOBJECT at ./test15.pl line 27.

Im thinking there might be something else missing in the SilverPeak.pm file and mapping things, i know its basic, the other .pms ones i looked through seem more comprehensive, feel like im almost there but not sure what to put in or edit

**Comment by JeroenvIS** [comment]
> alright, so youre not sure why its returning from its own specific sub-class this error- SNMP::Info::_global spsProductModel : SILVERPEAK-MGMT-MIB::spsProductModel.0 : 1.3.6.1.4.1.23867.3.1.1.1.2.0 SNMP::Info::_global(spsProductModel) NOSUCHOBJECT at ./test15.pl line 27.

No, not sure about that one. I always test subclasses through SNMP::Info with AutoSpecify on, never directly.

**Comment by alcatron** [comment]
Can you give me an example what i should do try test it? Do you see in myCode anything else im missing?I spent a week on this to try get it going but seems this product is so difficult to integrate.On 22 Jul 2024, at 18:33, Jeroen van Ingen Schenau ***@***.***> wrote:﻿

alright, so youre not sure why its returning from its own specific sub-class this error- SNMP::Info::_global spsProductModel : SILVERPEAK-MGMT-MIB::spsProductModel.0 : 1.3.6.1.4.1.23867.3.1.1.1.2.0 SNMP::Info::_global(spsProductModel) NOSUCHOBJECT at ./test15.pl line 27.

No, not sure about that one. I always test subclasses through SNMP::Info with AutoSpecify on, never directly.

**Comment by JeroenvIS** [comment]
If you want, I can try with the code that you provided, but I'd need a load of SNMP data from your device in order to simulate it (as I don't have access to a Silverpeak device myself).

A dump created with `snmprec` as described at https://github.com/netdisco/snmp-info/wiki/Simulating-Agents would be preferred. I can probably spend one or two hours on it later this week.

**Comment by alcatron** [comment]
Alright, i can do it, can i send it to you via a secure method ?On 22 Jul 2024, at 20:20, Jeroen van Ingen Schenau ***@***.***> wrote:﻿
If you want, I can try with the code that you provided, but I'd need a load of SNMP data from your device in order to simulate it (as I don't have access to a Silverpeak device myself).
A dump created with snmprec as described at https://github.com/netdisco/snmp-info/wiki/Simulating-Agents would be preferred. I can probably spend one or two hours on it later this week.

**Comment by JeroenvIS** [comment]
One secure method that I can suggest is to create a private github repo and give me access to it. You can remove it when we're done.

**Comment by alcatron** [comment]
ok I managed to finally crack it and got it working

Info.pm
```
=item SNMP::Info::Layer3::SilverPeak

# SilverPeak
        $objtype = 'SNMP::Info::Layer3::SilverPeak'
            if ( $soid =~ /^\.?1\.3\.6\.1\.4\.1\.23867/ );
```

SilverPeak.pm

```
package SNMP::Info::Layer3::SilverPeak;

use strict;
use warnings;
use Exporter;
use SNMP::Info::Layer3;

@SNMP::Info::Layer3::SilverPeak::ISA = qw/SNMP::Info::Layer3 Exporter/;
@SNMP::Info::Layer3::SilverPeak::EXPORT_OK = qw//;

our ($VERSION, %MIBS, %FUNCS, %GLOBALS, %MUNGE);

$VERSION = '3.70';

%MIBS = (
    %SNMP::Info::Layer3::MIBS,
    'SILVERPEAK-MGMT-MIB'    => 'spsSystemVersion',
    'SILVERPEAK-PRODUCTS-MIB' => 'spsProductModel',
);

%GLOBALS = (
    %SNMP::Info::Layer3::GLOBALS,
    'os_ver'       => 'spsSystemVersion.0',
    'product_model'=> 'spsProductModel.0',
    'serial'       => 'spsSystemSerial.0',
    'uptime'       => 'spsSystemUptime.0',
);

%FUNCS = (
    %SNMP::Info::Layer3::FUNCS,
);

%MUNGE = (
    %SNMP::Info::Layer3::MUNGE,
);

sub vendor {
    return 'silverpeak';
}

sub model {
    my $silverpeak = shift;
    my $model = $silverpeak->product_model();
    return $model if defined $model;
    return;
}

sub os {
    return 'silverpeak';
}

sub os_ver {
    my $silverpeak = shift;
    return $silverpeak->spsSystemVersion();
}

sub serial {
    my $silverpeak = shift;
    return $silverpeak->spsSystemSerial();
}

sub uptime {
    my $silverpeak = shift;
    return $silverpeak->spsSystemUptime();
}

1;

```
Output

![image](https://github.com/user-attachments/assets/fbff3287-0c9a-4ff8-87ae-9597f358d634)

**Comment by ollyg** [comment]
I implemented this in 099c3022 but I can't make the tests work as I've no idea how SNMP::Info tests are engineered. This means it can't be released, yet, sorry.
BTW it does look like netdisco-mibs already contains the SilverPeak MIBs (in silver-peak directory)

**Comment by alcatron** [comment]
Hi Oliver, those mibs are version 9.2 or something the latest mibs are 9.5 which ive uploaded on that link/thread. They just need updating.What do you mean by how SNMP::Info tests are engineered?On 23 Jul 2024, at 03:24, Oliver Gorwits ***@***.***> wrote:﻿
I implemented this in 099c302 but I can't make the tests work as I've no idea how SNMP::Info tests are engineered. This means it can't be released, yet, sorry.
BTW it does look like netdisco-mibs already contains the SilverPeak MIBs (in silver-peak directory)

**Comment by alcatron** [comment]
Hey Oliver, I made a test file that you can use to test, if this helps?

Create a mocktest.t file with execute rights

```
#!/usr/bin/perl
use strict;
use warnings;

# Mock SNMP::Info
{
    package Mock::SNMP::Info;
    sub new {
        my $class = shift;
        my %args = @_;
        return bless \%args, $class;
    }

    sub layers { return '01001100'; }
    sub sysDescr { return 'Silver Peak Systems, Inc. EC10104 Linux test-hostname 4.19.87-sps #1 SMP PREEMPT Sat Apr 8 03:24:48 UTC 2023 ECOS 9.2.5.0_94689 #1-dev 2023-06-15 10:55:27 x86_64 sptest@yocto-app-build6:unknown'; }
    sub sysObjectID { return '1.3.6.1.4.1.23867.3.1.1.1'; }
    sub spsSystemVersion { return '9.2.5.0_94689'; }
    sub spsProductModel { return 'EC10104'; }
    sub spsSystemSerial { return '00-1B-BC-2F-3F-90'; }
    sub spsSystemUptime { return '687865907'; }
}

# Mock the necessary methods
{
    package SNMP::Info::Layer3::SilverPeak;
    use base 'Mock::SNMP::Info';

    sub os_ver {
        my $self = shift;
        return $self->spsSystemVersion();
    }

    sub model {
        my $self = shift;
        return $self->spsProductModel();
    }

    sub serial {
        my $self = shift;
        return $self->spsSystemSerial();
    }

    sub uptime {
        my $self = shift;
        return $self->spsSystemUptime();
    }
}

# Test script
use Test::More tests => 4;

my $info = SNMP::Info::Layer3::SilverPeak->new();

is($info->os_ver(), '9.2.5.0_94689', 'OS Version matches');
is($info->model(), 'EC10104', 'Product Model matches');
is($info->serial(), '00-1B-BC-2F-3F-90', 'System Serial matches');
is($info->uptime(), '687865907', 'System Uptime matches');

done_testing();
```

Executing the test file..

```
[ mocktest]$ prove -v mocktest.t
mocktest.t .. 
1..4
ok 1 - OS Version matches
ok 2 - Product Model matches
ok 3 - System Serial matches
ok 4 - System Uptime matches
ok
All tests successful.
Files=1, Tests=4,  0 wallclock secs ( 0.04 usr  0.00 sys +  0.09 cusr  0.03 csys =  0.16 CPU)
Result: PASS
```

Methods for fetching specific attributes using the SilverPeak MIBs:
- os_ver for System Version
- model for Product Model
- serial for System Serial
- uptime for System Uptime

**Comment by JeroenvIS** [comment]
I've written SNMP::Info tests before; I'm a bit rusty at it, but need to catch up anyway - I have a local addition for Westermo industrial switches that I can finalize. Will give it a go in the next couple of days.

**Comment by ollyg** [comment]
> Hi Oliver, those mibs are version 9.2 or something the latest mibs are 9.5 which ive uploaded on that link/thread.

The netdisco-mibs analysis of the 9.5 mibs is that they're the same as the bundled ones, at least for the silver-peak items:

```
% EXTRAS/scripts/prepmibs  ~/Downloads/silver-peak
👀 Scanning submitted files
👀 Building MIBs baseline
✔ Index rebuilt (0 errors, 106 vendors, 4586 mibs).
= SILVERPEAK-MGMT-MIB is the same revision (SILVERPEAK-MGMT-MIB.txt ⇰ same/SILVERPEAK-MGMT-MIB.mib)
= SILVERPEAK-PRODUCTS-MIB is the same revision (SILVERPEAK-PRODUCTS-MIB.txt ⇰ same/SILVERPEAK-PRODUCTS-MIB.mib)
= SILVERPEAK-SMI is the same revision (SILVERPEAK-SMI.txt ⇰ same/SILVERPEAK-SMI.mib)
= SILVERPEAK-TC is the same revision (SILVERPEAK-TC.txt ⇰ same/SILVERPEAK-TC.mib)
⚠ file Readme.txt was skipped by our indexer
✘ IANA-ADDRESS-FAMILY-NUMBERS-MIB already known in rfc (IANA-ADDRESS-FAMILY-NUMBERS-MIB.txt ⇰ other/.../IANA-ADDRESS-FAMILY-NUMBERS-MIB.mib)
✘ IANA-LANGUAGE-MIB already known in rfc (IANA-LANGUAGE-MIB.txt ⇰ other/.../IANA-LANGUAGE-MIB.mib)
✘ IANAifType-MIB already known in rfc (IANAifType-MIB.txt ⇰ other/.../IANAIFTYPE-MIB.mib)
✘ IF-MIB already known in rfc (IF-MIB.txt ⇰ other/.../IF-MIB.mib)
✘ INET-ADDRESS-MIB already known in rfc (INET-ADDRESS-MIB.txt ⇰ other/.../INET-ADDRESS-MIB.mib)
✘ IP-MIB already known in rfc (IP-MIB.txt ⇰ other/.../IP-MIB.mib)
✘ RFC1155-SMI already known in rfc (RFC1155-SMI.txt ⇰ other/.../RFC1155-SMI.mib)
✘ RFC1213-MIB already known in rfc (RFC1213-MIB.txt ⇰ other/.../RFC1213-MIB.mib)
✘ SNMP-FRAMEWORK-MIB already known in rfc (SNMP-FRAMEWORK-MIB.txt ⇰ other/.../SNMP-FRAMEWORK-MIB.mib)
✘ SNMP-MPD-MIB already known in rfc (SNMP-MPD-MIB.txt ⇰ other/.../SNMP-MPD-MIB.mib)
✘ SNMP-NOTIFICATION-MIB already known in rfc (SNMP-NOTIFICATION-MIB.txt ⇰ other/.../SNMP-NOTIFICATION-MIB.mib)
✘ SNMP-TARGET-MIB already known in rfc (SNMP-TARGET-MIB.txt ⇰ other/.../SNMP-TARGET-MIB.mib)
✘ SNMP-USER-BASED-SM-MIB already known in rfc (SNMP-USER-BASED-SM-MIB.txt ⇰ other/.../SNMP-USER-BASED-SM-MIB.mib)
✘ SNMP-VIEW-BASED-ACM-MIB already known in rfc (SNMP-VIEW-BASED-ACM-MIB.txt ⇰ other/.../SNMP-VIEW-BASED-ACM-MIB.mib)
✘ SNMPv2-CONF already known in rfc (SNMPv2-CONF.txt ⇰ other/.../SNMPV2-CONF.mib)
✘ SNMPv2-MIB already known in rfc (SNMPv2-MIB.txt ⇰ other/.../SNMPV2-MIB.mib)
✘ SNMPv2-SMI already known in rfc (SNMPv2-SMI.txt ⇰ other/.../SNMPV2-SMI.mib)
✘ SNMPv2-TC already known in rfc (SNMPv2-TC.txt ⇰ other/.../SNMPV2-TC.mib)
✔ MIBs ready for import.
```

**Comment by alcatron** [comment]
Hi Oliver, version 9.5 of the products mib has been updated with more models of the hardware thats all the changes are.On 26 Jul 2024, at 01:42, Oliver Gorwits ***@***.***> wrote:﻿

Hi Oliver, those mibs are version 9.2 or something the latest mibs are 9.5 which ive uploaded on that link/thread.

The netdisco-mibs analysis of the 9.5 mibs is that they're the same as the bundled ones, at least for the silver-peak items:
% EXTRAS/scripts/prepmibs  ~/Downloads/silver-peak
👀 Scanning submitted files
👀 Building MIBs baseline
✔ Index rebuilt (0 errors, 106 vendors, 4586 mibs).
= SILVERPEAK-MGMT-MIB is the same revision (SILVERPEAK-MGMT-MIB.txt ⇰ same/SILVERPEAK-MGMT-MIB.mib)
= SILVERPEAK-PRODUCTS-MIB is the same revision (SILVERPEAK-PRODUCTS-MIB.txt ⇰ same/SILVERPEAK-PRODUCTS-MIB.mib)
= SILVERPEAK-SMI is the same revision (SILVERPEAK-SMI.txt ⇰ same/SILVERPEAK-SMI.mib)
= SILVERPEAK-TC is the same revision (SILVERPEAK-TC.txt ⇰ same/SILVERPEAK-TC.mib)
⚠ file Readme.txt was skipped by our indexer
✘ IANA-ADDRESS-FAMILY-NUMBERS-MIB already known in rfc (IANA-ADDRESS-FAMILY-NUMBERS-MIB.txt ⇰ other/.../IANA-ADDRESS-FAMILY-NUMBERS-MIB.mib)
✘ IANA-LANGUAGE-MIB already known in rfc (IANA-LANGUAGE-MIB.txt ⇰ other/.../IANA-LANGUAGE-MIB.mib)
✘ IANAifType-MIB already known in rfc (IANAifType-MIB.txt ⇰ other/.../IANAIFTYPE-MIB.mib)
✘ IF-MIB already known in rfc (IF-MIB.txt ⇰ other/.../IF-MIB.mib)
✘ INET-ADDRESS-MIB already known in rfc (INET-ADDRESS-MIB.txt ⇰ other/.../INET-ADDRESS-MIB.mib)
✘ IP-MIB already known in rfc (IP-MIB.txt ⇰ other/.../IP-MIB.mib)
✘ RFC1155-SMI already known in rfc (RFC1155-SMI.txt ⇰ other/.../RFC1155-SMI.mib)
✘ RFC1213-MIB already known in rfc (RFC1213-MIB.txt ⇰ other/.../RFC1213-MIB.mib)
✘ SNMP-FRAMEWORK-MIB already known in rfc (SNMP-FRAMEWORK-MIB.txt ⇰ other/.../SNMP-FRAMEWORK-MIB.mib)
✘ SNMP-MPD-MIB already known in rfc (SNMP-MPD-MIB.txt ⇰ other/.../SNMP-MPD-MIB.mib)
✘ SNMP-NOTIFICATION-MIB already known in rfc (SNMP-NOTIFICATION-MIB.txt ⇰ other/.../SNMP-NOTIFICATION-MIB.mib)
✘ SNMP-TARGET-MIB already known in rfc (SNMP-TARGET-MIB.txt ⇰ other/.../SNMP-TARGET-MIB.mib)
✘ SNMP-USER-BASED-SM-MIB already known in rfc (SNMP-USER-BASED-SM-MIB.txt ⇰ other/.../SNMP-USER-BASED-SM-MIB.mib)
✘ SNMP-VIEW-BASED-ACM-MIB already known in rfc (SNMP-VIEW-BASED-ACM-MIB.txt ⇰ other/.../SNMP-VIEW-BASED-ACM-MIB.mib)
✘ SNMPv2-CONF already known in rfc (SNMPv2-CONF.txt ⇰ other/.../SNMPV2-CONF.mib)
✘ SNMPv2-MIB already known in rfc (SNMPv2-MIB.txt ⇰ other/.../SNMPV2-MIB.mib)
✘ SNMPv2-SMI already known in rfc (SNMPv2-SMI.txt ⇰ other/.../SNMPV2-SMI.mib)
✘ SNMPv2-TC already known in rfc (SNMPv2-TC.txt ⇰ other/.../SNMPV2-TC.mib)
✔ MIBs ready for import.

**Comment by ollyg** [comment]
Okay so they updated the content of the products MIB and didn't bump the version (naughty!). We can just copy the new version in if the changes are clean.

**Comment by alcatron** [comment]
Alright cool hows my snmp integration work so far have you done any test?So far im using my modifications in our environment with no problems.On 26 Jul 2024, at 17:49, Oliver Gorwits ***@***.***> wrote:﻿
Okay so they updated the content of the products MIB and didn't bump the version (naughty!). We can just copy the new version in if the changes are clean.

**Comment by alcatron** [comment]
Hi Oliver , are you any closer to integrating this into SNMP info?

 

 

From: Muris ***@***.***>
Date: Friday 26 July 2024 at 17:56
To: netdisco/snmp-info ***@***.***>
Cc: netdisco/snmp-info ***@***.***>, Author ***@***.***>
Subject: Re: [netdisco/snmp-info] Silverpeak devices (Issue #524)

 

Alright cool hows my snmp integration work so far have you done any test?

 

So far im using my modifications in our environment with no problems.

 




On 26 Jul 2024, at 17:49, Oliver Gorwits ***@***.***> wrote:

﻿

Okay so they updated the content of the products MIB and didn't bump the version (naughty!). We can just copy the new version in if the changes are clean.

**Comment by JeroenvIS** [comment]
FYI, I failed to get a working dev environment to get the tests done, before leaving on holiday. It's still on my ToDo list to get this working again.

Regards,
Jeroen

Get BlueMail for Android<https://bluemail.me/>
On Aug 12, 2024, at 09:22, Muris ***@***.******@***.***>> wrote:

Hi Oliver , are you any closer to integrating this into SNMP info?





From: Muris ***@***.***>
Date: Friday 26 July 2024 at 17:56
To: netdisco/snmp-info ***@***.***>
Cc: netdisco/snmp-info ***@***.***>, Author ***@***.***>
Subject: Re: [netdisco/snmp-info] Silverpeak devices (Issue #524)



Alright cool hows my snmp integration work so far have you done any test?



So far im using my modifications in our environment with no problems.






On 26 Jul 2024, at 17:49, Oliver Gorwits ***@***.***> wrote:

﻿

Okay so they updated the content of the products MIB and didn't bump the version (naughty!). We can just copy the new version in if the changes are clean.

**Comment by alcatron** [comment]
I worked for a while getting this integrated and making it work, not sure why it’s taking so long to add it into SNMP info.

 

I want to update to the next netdisco revision but I’d like it with the full SNMP info silverpeak support so I don’t have to hack the files manually.. 

 

I’ll hold tight a bit longer 😊

 

From: Jeroen van Ingen Schenau ***@***.***>
Reply to: netdisco/snmp-info ***@***.***>
Date: Monday 12 August 2024 at 8:15 PM
To: netdisco/snmp-info ***@***.***>
Cc: Muris ***@***.***>, Author ***@***.***>
Subject: Re: [netdisco/snmp-info] Silverpeak devices (Issue #524)

 

FYI, I failed to get a working dev environment to get the tests done, before leaving on holiday. It's still on my ToDo list to get this working again. 

Regards, 
Jeroen 

Get BlueMail for Android<https://bluemail.me/> 
On Aug 12, 2024, at 09:22, Muris ***@***.******@***.***>> wrote: 

Hi Oliver , are you any closer to integrating this into SNMP info? 





From: Muris ***@***.***> 
Date: Friday 26 July 2024 at 17:56 
To: netdisco/snmp-info ***@***.***> 
Cc: netdisco/snmp-info ***@***.***>, Author ***@***.***> 
Subject: Re: [netdisco/snmp-info] Silverpeak devices (Issue #524) 



Alright cool hows my snmp integration work so far have you done any test? 



So far im using my modifications in our environment with no problems. 






On 26 Jul 2024, at 17:49, Oliver Gorwits ***@***.***> wrote: 

﻿ 

Okay so they updated the content of the products MIB and didn't bump the version (naughty!). We can just copy the new version in if the changes are clean.

**Comment by alcatron** [comment]
this can be resolved and closed now as its implemented
