### ISSUE TITLE
Cisco Small Business/Linksys switches incorrectly detected

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#60]
Linksys and Cisco SBS devices use their own MIBs. It appears that 

1: Not all are currently incorporated into netdisco
2: Those that are (SG300 family) may be using the wrong MIBs, as they're not being enumerated correctly.

If you don't have a Cisco login, one can be setup to grab MIBs and related files  without needing CCNA or higher qualifications.

http://tools.cisco.com/ITDIT/MIBS/servlet/index

Non IOS MIBs are listed at http://www.cisco.com/public/sw-center/netmgmt/cmtk/mibs.shtml, although most of the attached mibs are buried in the support forums.

List follows:

"unknown 	enterprises.3955.6.3.2008.1 	1"
Linksys SRW2008P - 6-port Gigabit Switch with 2 Combo ports, WebView and PoE

"linksys 	48-Port 10/100/1000 Gigabit Switch with WebView 	2"
Linksys SRW2048

The SRW mib zips attached should fully cover these

"unknown 	enterprises.3955.6.9.2024.1 	4"
Cisco SPS2024 "small provider switch"

The SPS2xx MIB zip covers these

"cisco 	SB.83.20.1 	1"
(This is a SG300-20)
"cisco 	SG300-20 20-Port Gigabit Managed Switch 	2"
"cisco 	SG300-28 28-Port Gigabit Managed Switch 	1"
"cisco 	SG300-52 52-Port Gigabit Managed Switch 	2"

Sx300 MIB zip - this covers SF300, SG300 and SG500 family

Older versions at http://software.cisco.com/download/release.html?mdfid=283019611&flowid=&softwareid=283415684&release=1.2.9&relind=null&rellifecycle=null&reltype=null

"cisco 	48-port 10/100/1000 Ethernet Switch 	1"
 Cisco/Linksys SGE2048

The SGE MIB file will cover this family (and SFExxxx)

http://software.cisco.com/download/release.html?mdfid=282414067&softwareid=283415684&release=3.0.0&relind=AVAILABLE&rellifecycle=&reltype=latest

Reported by: stoatwblr

Original Ticket: [snmp-info/bugs/61](https://sourceforge.net/p/snmp-info/bugs/61)

**Comment by jeneric** [comment]
This is a netdisco-mibs issue. The ciscosb directory exists within netdisco-mibs containing a version of the MIBs attached to the original ticket. However, it appears that linksys doesn't have a traditional "products" MIB which would resolve the individual sysObjectID's. Closing the ticket since the netdisco-mibs issue appears to have been implemented.
