### ISSUE TITLE
ZyXEL (X)GS1900 family MIB

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#61]
"unknown 	enterprises.890.1.5.8.66 	1"

ZyXel XGS1910-48 - this is covered by the ZyXEL GS1900 MIB

NOTE: this is being picked up as a DSLAM at the moment and running discovery on it causes the process to blow out past 48Gb on the system here, before being OOM-killed. Commenting out the DSLAM line solves it but a better cure is needed.

http://www.zyxel.com/euosearch/dl-search.aspx?mci_country=uk&mci_lang=en&keyword=MIB&submit=Submit

Reported by: stoatwblr

Original Ticket: [snmp-info/bugs/62](https://sourceforge.net/p/snmp-info/bugs/62)

**Comment by ollyg** [comment]
I think the DSLAM bug was fixed. Keeping this open to check MIB inclusion.

**Comment by jeneric** [comment]
The OOM-killed bug was actually due to a recursive call in the layers method. This has been fixed in the commit referenced above. The MIBs are not used in any of the snmp-info classes. Closing the issue, if there is still a desire for the MIBs to be added, please open a ticket in netdisco-mibs.
