### ISSUE TITLE
HP J0928(A/B) detection

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#62]
These are particularly dain bramaged devices which don't seem to report much (including not reporting which VLANs their ports are using)

hp 	1800-24G 	14
hp 	J9028B 	19

These are the J9028A and B models (B removed the fan, otherwise identical)

Not picking up VLANs, adjacent nodes and neighbours very well.

hp 	1810G-8 	1

J9449A - not everything is detected properly but mostly ok.

hp 	2524 	1

J4813A - seems to work fine.

If at all possible, netdisco inventory results should return the Jxxxx number as well as the marketing name, as this part is the canonical item - HP sell a few devices with the same name and different internals.

Latest HP mibsets attached (May 2014)

https://h10145.www1.hp.com/Downloads/DownloadSoftware.aspx?SoftwareReleaseUId=11143&ProductNumber=J9028B&lang=en,en&cc=us,us&prodSeriesId=3231819&SerialNumber=&PurchaseDate=

Reported by: stoatwblr

Original Ticket: [snmp-info/bugs/63](https://sourceforge.net/p/snmp-info/bugs/63)

**Comment by ollyg** [comment]
I went to the link for HP mibs and downloaded the 28-Jan-2016 bundle and managed to import them.

**Comment by jeneric** [comment]
MIBs were updated and J numbers mentioned in ticket appear in the HP class. It is not apparent if there is anything else to do with this ticket.
