### ISSUE TITLE
Lists of ports/neighbors miss LLDP-neighbors

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#64]
On a Cisco-switch I have enabled CDP and LLDP. The core-network runs CDP and neighbors show up fine. The LLDP-neighbors however don't appear as "connected devices", although they show up in a "sh lldp" on the Cisco-switch.
Could it be that netdisco does not see them during a query through SNMP for some reason? Are the LLDP-neighbors below some separate tree in SNMP maybe?

Reported by: neufeind

Original Ticket: [snmp-info/bugs/65](https://sourceforge.net/p/snmp-info/bugs/65)

**Comment by ollyg** [comment]
Stefan never replied to Jeroen, so closing.
