### ISSUE TITLE
Invalid vendor ID in Info.pm

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/snmp-info#66]
There was a mesage from Ilya Rassadin <elcamlost@gm...> - 2015-07-16 13:44:11 at [snmp-info] mailing list.
I conform the same issue. 
Here follows Ilya's message text:

Hi!

I'm just starting usage of SNMP::Info module and found unpleasant bug.

I mostly need SNPM::Info to retrieve data from D-Link devices but when I
instantiate new SNMP::Info object with AutoSpecify = 1

$snmp_session = SNMP::Info->new(
    'Debug'             => 1,
    'AutoSpecify'       => 1,
    'BigInt'            => 1,
    'BulkWalk'          => 1,
    'BulkRepeaters'     => 20,
    'IgnoreNetSNMPConf' => 1,
    'LoopDetect'        => 1,
    'DestHost'          => 'my-host-name',
    'Community'         => 'public',
    'Version'           => 2,
);

I get this error
Cannot find module (RADLAN-HWENVIROMENT): At line 1 in (none)
The RADLAN-HWENVIROMENT did not load. See README for
SNMP::Info::Layer3::Dell

I investigated Info.pm sources (
https://metacpan.org/source/OLIVER/SNMP-Info-3.28/Info.pm#L1507) and found
that D-Link Entrerpise ID 171 reserved for DELL devices

It's wrong, 171 is official Enterprise ID for D-Link devices and 674 is
official for DELL (see
https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers)

Please, fix it.

Reported by: nobody

Original Ticket: [snmp-info/bugs/68](https://sourceforge.net/p/snmp-info/bugs/68)

**Comment by ollyg** [comment]
This isn't a bug - the Layer3::Dell class does support D-Link (and IBM and Linksys). I presume some M&A legacy...

The error seems to be MIB loading (red herring).
